### ISSUE TITLE
Upgrade Java Quickstarters to Java 17 and Springboot 3.x

### ISSUE THREAD

**Issue by amardeep2006** [dapr/quickstarts#1042]
## Describe the feature

I noticed that Java examples can be improved by making following changes:

1. Use Java 17 as baseline in ReadME
2. Upgrade example to use Springboot 3.x.x
3. Use Java records instead of Lombok . One less dependency to manage. (In future)
4. Start adding test cases (gradually) .

Please share your feedback on this. I am interested in sending PR if you are good with these suggestions.

**Comment by amardeep2006** [comment]
I have raised a PR https://github.com/dapr/quickstarts/pull/1043
1. Java Readme now correctly asks to use Java 17 as code base already needed Java17
2. Upgraded springboot t 3.3.1
3. Bumped up other dependencies as well.

I have replaced Lombok . Will raise separate PR if needed.

**Comment by msfussell** [comment]
Closing this issue. @amardeep2006 THANK YOU for this amazing contribution!
