### ISSUE TITLE
javascript quickstarts need npm audit fixes

### ISSUE THREAD

**Issue by joebowbeer** [dapr/quickstarts#1063]
In almost every javascript quickstart (and probably tutorial) the `npm i` installation in each package folder reports audit findings.

Most are fixed by `npm audit fix`

In some cases an upgrade to axios v1 is needed, which requires a `npm audit fix --force`

Dependabot should be able to generate PRs for these.

This is a sequel to #1054 (which reported pub_sub audit findings)

## Expected Behavior

Running `npm i` in a javascript folder with package*.json does not report npm audit findings.

## Actual Behavior

A handful of audit findings reported in each folder.

## Steps to Reproduce the Problem

1. cd to source folder, e.g., configuration/javascript/sdk/order-processor
2. `npm i`

**Comment by joebowbeer** [comment]
/assign joebowbeer

I will create a PR for this

**Comment by paulyuk** [comment]
If we can rebase and sync your PR @joebowbeer I'd love to take it for 1.14 release.  Please track in that issue

**Comment by joebowbeer** [comment]
Thanks. I finished rebasing my branch on 1.14

**Comment by paulyuk** [comment]
Fixed by #1081, merged!
