### ISSUE TITLE
SDK Go Update Quickstart to use DaprWorkflowClient

### ISSUE THREAD

**Issue by elena-kolevska** [dapr/quickstarts#1120]
https://github.com/dapr/quickstarts/issues/1118

**Comment by elena-kolevska** [comment]
Already uses the workflow client

**Comment by jake-engelberg** [comment]
I don't see any usage of the deprecated workflow methods...:
(`StartWorkflowBeta1()`, `GetWorkflowBeta1()`, `ResumeWorkflowBeta1()`, etc)
...from `github.com/dapr/go-sdk/client` in the go workflow quickstart.
The client package is only being used for state store in the quickstart.
[workflows/go/sdk/order-processor/main.go:139](https://github.com/dapr/quickstarts/blob/9e9cb5e862e38d21f001f344066c0bb4e6ba35c0/workflows/go/sdk/order-processor/main.go#L139)


Instead, I already see usage of the new `github.com/dapr/go-sdk/workflow` methods:
(`ScheduleNewWorkflow()`, `FetchWorkflowMetadata()`, `RaiseEvent()`, etc)
[workflows/go/sdk/order-processor/main.go:84](https://github.com/dapr/quickstarts/blob/9e9cb5e862e38d21f001f344066c0bb4e6ba35c0/workflows/go/sdk/order-processor/main.go#L84)
