### ISSUE TITLE
Issues while trying to run 4.pub-sub sample example

### ISSUE THREAD

**Issue by hugobarona** [dapr/quickstarts#206]
## Expected Behavior

Followed all steps according to documentation, and once the subscribers are running and I post an event to a given topic (A,B,C), I would expect the node or python to receive the event.

## Actual Behavior

Both node and python subscribers do not receive the event.

## Steps to Reproduce the Problem

I followed all steps on the documentation to run the sample locally. Logs attached.
[python-logs.txt](https://github.com/dapr/samples/files/4603284/python-logs.txt)
[nodejs-logs.txt](https://github.com/dapr/samples/files/4603285/nodejs-logs.txt)

**Comment by hugobarona** [comment]
I noticed the following errors on the logs

== DAPR == time="2020-05-09T12:17:28.4005944+01:00" level=warning msg="redis streams: ERR unknown command 'xgroup'" instance=<MACHINE-NAME> scope=dapr.contrib type=log ver=0.7.0       
== DAPR == time="2020-05-09T12:17:28.4005944+01:00" level=warning msg="redis streams: ERR unknown command 'xgroup'" instance=<MACHINE-NAME> scope=dapr.contrib type=log ver=0.7.0       

== DAPR == time="2020-05-09T12:17:28.4005944+01:00" level=error msg="redis streams: error reading from stream C: ERR unknown command 'xreadgroup'" instance=<MACHINE-NAME> scope=dapr.contrib type=log ver=0.7.0
== DAPR == time="2020-05-09T12:17:28.4015282+01:00" level=error msg="redis streams: error reading from stream A: ERR unknown command 'xreadgroup'" instance=<MACHINE-NAME> scope=dapr.contrib type=log ver=0.7.0


Is there a chance of problems with the version of redis?

**Comment by afsalcodehack** [comment]
> I noticed the following errors on the logs
> 
> == DAPR == time="2020-05-09T12:17:28.4005944+01:00" level=warning msg="redis streams: ERR unknown command 'xgroup'" instance= scope=dapr.contrib type=log ver=0.7.0
> == DAPR == time="2020-05-09T12:17:28.4005944+01:00" level=warning msg="redis streams: ERR unknown command 'xgroup'" instance= scope=dapr.contrib type=log ver=0.7.0
> 
> == DAPR == time="2020-05-09T12:17:28.4005944+01:00" level=error msg="redis streams: error reading from stream C: ERR unknown command 'xreadgroup'" instance= scope=dapr.contrib type=log ver=0.7.0
> == DAPR == time="2020-05-09T12:17:28.4015282+01:00" level=error msg="redis streams: error reading from stream A: ERR unknown command 'xreadgroup'" instance= scope=dapr.contrib type=log ver=0.7.0
> 
> Is there a chance of problems with the version of redis?

I have same issue let me know there is any clue

**Comment by afsalcodehack** [comment]
i think problem related to this issue 
https://github.com/bitnami/bitnami-docker-redis/issues/152

**Comment by hugobarona** [comment]
Well, I think it is not my case since the instance of Redis is running, I am able to use the redis-cli to interact with the Redis instance locally. And also I am able to run example 1 locally.

**Comment by afsalcodehack** [comment]
My redis not running im getting this error form log

`C:\Users\aa>kubectl logs redis-master-0 -p
[38;5;6m [38;5;5m12:24:23.62 [0m[38;5;2mINFO [0m ==> ** Starting Redis **
1:C 09 May 2020 12:24:23.632 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
1:C 09 May 2020 12:24:23.632 # Redis version=6.0.1, bits=64, commit=00000000, modified=0, pid=1, just started
1:C 09 May 2020 12:24:23.632 # Configuration loaded
1:M 09 May 2020 12:24:23.635 # **Can't open the append-only file: Permission denied**`

**Comment by hugobarona** [comment]
Tried a different component for the pubsub, servicebus in this case and it not working as well. No sign of messages on the subscriber, but the messages are active on the topic, since I can see them on the dashboards via Azure Portal.
 
```
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: messagebus
spec:
  type: pubsub.servicebus
  metadata:
  - name: connectionString
    value: "Endpoint=sb://<ServiceBusName>.servicebus.windows.net/;SharedAccessKeyName=node-read;SharedAccessKey=<POLICY-KEY>;EntityPath=topic1"
  - name: consumerID
    value: "nodeTopicA"
```

Note: I replaced the name of the service bus instance and the key for obvious reasons.

The _topic1_ is the name of the Topic I created on the SB instance.
The _nodeTopicA_ is the name of the subscription I created on the topic.

@amanbha  Any idea what's wrong with this now?

**Comment by hugobarona** [comment]
Just an update on this. I was able to finally put this working using Service Bus. I had to look to your component's source code, and I figured out the configs required and the relevant changes to the components' configs on the sample 4. 

The redis is still an issue apparently. According to my logs it does not recognize commands such as xreadgroup, xgroup. It looks to me that sounds like a version problem?

**Comment by pruthvidhodda** [comment]
@hugobarona what version of redis are you using?

**Comment by yaron2** [comment]
> Just an update on this. I was able to finally put this working using Service Bus. I had to look to your component's source code, and I figured out the configs required and the relevant changes to the components' configs on the sample 4.
> 
> The redis is still an issue apparently. According to my logs it does not recognize commands such as xreadgroup, xgroup. It looks to me that sounds like a version problem?

You need Redis > 5

**Comment by hugobarona** [comment]
I am running this on Windows, so I have redis for windows installed (3.x). What would be the suggestion on this case? Create a container and pull redis image with Version 5 or 6?

**Comment by yaron2** [comment]
> I am running this on Windows, so I have redis for windows installed (3.x). What would be the suggestion on this case? Create a container and pull redis image with Version 5 or 6?

If you have Docker installed, `dapr init` will set it up for you.

**Comment by hugobarona** [comment]
Yaron I have docker installed and I am running already few samples. So I can use the redis container available, configured by the dapr init?

**Comment by yaron2** [comment]
> Yaron I have docker installed and I am running already few samples. So I can use the redis container available, configured by the dapr init?

Yes

**Comment by hugobarona** [comment]
Great. I will give it a try on the next few days and let you know.

**Comment by amanbha** [comment]
@hugobarona let us know if its working for you now,

**Comment by ChrisProlls** [comment]
@hugobarona have you tried the example with Redis container ?
The sample 4 doesn't work on Kubernetes, my subscriber doesn't receives messages, but my Redis is correctly up and running.

**Comment by ziez** [comment]
I had the same behavior as @ChrisProlls until I replaced `subscriptions = [{'topic': 'A', 'route': 'a'}, {'topic': 'C', 'route': 'c'}]`  with  `subscriptions = ['a', 'c']` in python service. I believe the same is valid for node service.

It is not clear now how to provide a route, if it differs from topic.

**Comment by ChrisProlls** [comment]
@ziez did you use Dapr 7.0 or 6.0 ?
With 7.0 it doesn't work for me ...

**Comment by ziez** [comment]
@ChrisProlls , the latest:

> \> dapr --version 
> CLI version: 0.7.0 
> Runtime version: 0.7.1

**Comment by yaron2** [comment]
@ziez @ChrisProlls the docs on master branch are updated with the master branch for Dapr, which has a breaking change to subscriptions.

If you are using a versioned release, you need to look at the corresponding docs:

https://github.com/dapr/samples#supported-dapr-runtime-version

**Comment by ziez** [comment]
@yaron2 , oh, I see now. It wasn't intuitive that you have to checkout tagged commit even for 0.7.1.

Is there any chance btw to install the nightly build or something about? Something like `dapr init --runtime-version nightly`?

**Comment by ChrisProlls** [comment]
@yaron2 yep you're right, I checkout the sample into the v0.7.0 branch and it's all working now !!

**Comment by yaron2** [comment]
@ChrisProlls great!

@ziez indeed. `dapr init --runtime-version edge`.

**Comment by ziez** [comment]
@yaron2 , just installed dapr runtime 0.8.0 and try to run samples from tag v0.8.0 with no success. It looks like dapr does not call `/dapr/subscribe` at all.
btw. `dapr init --runtime-version edge` fails with a message `error downloading Dapr binary: runtime version not found`

**Comment by yaron2** [comment]
@ziez can you post the Dapr logs here?

**Comment by ziez** [comment]
@yaron2 , unfortunately not. Just removed everything and re-installed once again. Now it works like a charm. Seems that something was not updated well despite I was following all "Upgrading to Dapr 0.8.0" instructions.

**Comment by yaron2** [comment]
@hugobarona is everything working?

**Comment by wcs1only** [comment]
We haven't gotten any traction on this in 6 months, and v0.8.0 is no longer supported, so I'm going to go ahead and close this issue. Feel free to re-open it or create a new issue if you are still having trouble on the latest version (v1.0.0).
