### ISSUE TITLE
Extend the requirements for Python in sample 3.distributed-calculator

### ISSUE THREAD

**Issue by martinriedel** [dapr/quickstarts#217]
- Installation of python packages **flask** and **flask-cors** are missing in section 4 of [Running the sample locally](https://github.com/dapr/samples/tree/master/3.distributed-calculator#running-the-sample-locally)

- The environment variable for the flask app is wrong and should be **8000** under Windows like it's on Linux/Mac OS

**Comment by wcs1only** [comment]
Python requirements were updated via #358, and the FLASK_RUN_PORT is now consistent over Windows/Linux/Mac OS
