### ISSUE TITLE
Sample 6 (Functions and KEDA) Redis Install Failure - Utilize Bitnami repo

### ISSUE THREAD

**Issue by kakridge** [dapr/quickstarts#256]
## Expected Behavior

Expect Redis chart to be installed as part of setup.ps1

## Actual Behavior

Redis install fails.  Error reported:
Installing Redis as the Dapr state store on daprsamples-cluster...
Error: failed to download "stable/redis" (hint: running `helm repo update` may help)

## Steps to Reproduce the Problem

Given a fresh install of Helm 3 (without previous install of Helm 2), clone samples and run setup.ps1.  
Helm 3 does not add the stable repo automatically (unlike Helm 2). 
In addition, per [this document](https://github.com/helm/charts/tree/master/stable/redis#this-helm-chart-is-deprecated), the stable/redis chart is deprecated and bitnami/redis should be used (like in other samples).

**Comment by orizohar** [comment]
KEDA sample  was removed
