### ISSUE TITLE
Access is denied while exiting the app 

### ISSUE THREAD

**Issue by nskarakoc** [dapr/quickstarts#279]
I am currently running hello world sample on Windows 10. I am able run entire tutorial without any problems, but when I try to stop node app with CTRL+C, I get following:

```
terminated signal received: shutting down
Exited Dapr successfully
Error exiting App: TerminateProcess: Access is denied.
```

So, it is failing to exit the app. Any ideas why?

Note: Python app can be exited with CTRL+C without any issues.

**Comment by wcs1only** [comment]
So, this has to do with the way Windows spawns processes and how CTRL-C events get propagated from the terminal. In Windows, when you send CTRL-C everything that is attached to the terminal gets the CTRL-C event, so there is a race between who gets the event first, the Dapr CLI or your app. 

We're actually doing some improvements on this behavior in the CLI via: https://github.com/dapr/cli/issues/695

In the mean time, if you are looking to have a clean shutdown, if you use ```dapr stop --app-id <your_app>```, you should get a race free shutdown behavior.
