### ISSUE TITLE
secretstore quickstart - Add instruction to run locally

### ISSUE THREAD

**Issue by orizohar** [dapr/quickstarts#287]
Currently this quickstart only shows how to run on Kubernetes using the Kubernetes secret store. As with other quickstarts, this should also include a section for running locally (using the local secret store)

**Comment by msfussell** [comment]
Also it should be made clear in this quickstart that the name of the file become the name of the metadata to retrieve the secret and has to be the same. This line
kubectl create secret generic mysecret --from-file ./secret

If a file name with an extension is used which is common on Windows (e.g. secret.txt) or a file name other than "secret" is used, the code fails.
