### ISSUE TITLE
Move templates into dapr org and create language templates

### ISSUE THREAD

**Issue by mukundansundar** [dapr/quickstarts#294]
## Describe the proposal
The proposal is to move the templates seen here 
https://github.com/mchmarny?tab=repositories&q=dapr-*-template&type=&language=
into dapr org.

Additionally similar to go language template code, we could potentially have the code for other languages like Python or C#. 

This would potentially create a templates repo within dapr and additionally templates for each language and associated files might be organized into sub folders. 

@orizohar @mchmarny @msfussell

**Comment by mchmarny** [comment]
Once Dapr v0.10 lands, I'll update the 4 go templates and initiate transfer to the Dapr org

**Comment by orizohar** [comment]
@mchmarny @mukundansundar is this still relevant for this repo?

**Comment by paulyuk** [comment]
We've made multi language versions in feature/new_quickstarts

It's in our plan to do a Cron binding example.  I think this is resolved by that. Is there anything else we want @mukundansundar ?

**Comment by amulyavarote** [comment]
We have a different structure for this repo now. Hence closing this issue.
