### ISSUE TITLE
Fix documentation reference on hello-kubernetes example

### ISSUE THREAD

**Issue by fpaganetto** [dapr/quickstarts#303]
## Describe the proposal

I noticed the link on the [hello-kubernetes](https://github.com/dapr/quickstarts/tree/master/hello-kubernetes) example, that links to the previous one `Hello World` example is broken.

![image](https://user-images.githubusercontent.com/11998636/93831033-2eb9e100-fc48-11ea-9309-e311b267aae3.png)

To fix that, it needs to remove the characters `1.` 

This is not exactly a bug, so I created a proposal to track this change.

**Comment by tcnghia** [comment]
Closed by #304
