### ISSUE TITLE
Resolve high severity security dependabot alerts

### ISSUE THREAD

**Issue by mchmarny** [dapr/quickstarts#315]
https://github.com/dapr/dapr/network/alerts

**Comment by orizohar** [comment]
The ones to fix as they show up for me today are as follows:

1. Upgrade `node-fetch` to version 2.6.1 or later. (used in hello-world and binding/nodeapp
1. Upgrade `object-path` to version 0.11.5 or later (used in distributed calculator react calculator service)
1. Upgrade `node-forge` to version 0.10.0 or later. (used in distributed calculator react calculator service)

![image](https://user-images.githubusercontent.com/10497127/98851211-cc40be00-240a-11eb-8d77-607ac6af7539.png)

**Comment by orizohar** [comment]
Alert number has now raised to 13 (7 high severity) up from 4

**Comment by mchmarny** [comment]
Long term we need to figure out how to not depend on 1/2 of the internet in our quickstart node examples. I'm not a node expert but can we refactor the `react-form` dep out?

**Comment by orizohar** [comment]
I actually think we may want to consider retiring the distributed calc altogether - it has a lot of dependencies because it is using a lot of languages but really Dapr APIs are only called from the react app. This means a lot of pre-requisites and issues like this with little benefit in terms of showing Dapr capabilities

**Comment by mchmarny** [comment]
The number of dependancies doesn't have anything to do with the fact that that the app is distributed. The node apps themselves depend on `body-parser`, `cors`, `express`, request` directly and these have 10s of indirect dependancies each hence large number of [security warnings in alert](https://github.com/dapr/quickstarts/network/alerts). The main objective of the quickstart is to showcase Dapr capability so to that end we should limiting the number of dependancies in quickstart apps which in turn will drastically decrease the number of these alerts.

**Comment by amulyavarote** [comment]
We now have a different Quickstarts structure. Please reopen if there is more info/activity.
