### ISSUE TITLE
Document steps to setup allow lists feature for self hosted mode

### ISSUE THREAD

**Issue by vinayada1** [dapr/quickstarts#317]
## Expected Behavior

Document the steps needed to setup the certificates that is required to attach the SPIFFE id and apply access control policies as specified in the allow lists for service invocation

**Comment by msfussell** [comment]
Also see this doc issue https://github.com/dapr/docs/issues/851

**Comment by orizohar** [comment]
Why do we need to include this in the quickstarts? This seems like a scenario beyond the basic usage of the feature. Quickstarts don't need to be exhaustive

**Comment by vinayada1** [comment]
We had initially planned to add the allowlists feature to quickstarts and that's when this was filed. We can close this issue and keep the one that is for updating docs: https://github.com/dapr/docs/issues/851
