### ISSUE TITLE
Observability quickstart not showing traces as expected

### ISSUE THREAD

**Issue by arielmoraes** [dapr/quickstarts#319]
By following the observability readme we expect to see the chained traces but instead the follow traces are shown:

![image](https://user-images.githubusercontent.com/6741634/96539843-785f1100-1272-11eb-801c-c080e04cb9dc.png)

All configurations were double checked against the readme.

Is that somehow related to the W3C headers (traceparent and tracestate)?

**EDIT**
It seems the only traces being recorded are the ones generated by the dapr sidecar container

**Comment by CCGAC-Andreas-Riehl** [comment]
Furthermore the "data" section is not shown.
According to the quickstart sample the operands should be traced, but they are not traced.

**Comment by amulyavarote** [comment]
Closing this as we have a new version of Quickstarts. Please reopen if there is more info/activity.
