### ISSUE TITLE
A follow-up bug of a previous issue

### ISSUE THREAD

**Issue by AI-Marvel** [dapr/quickstarts#334]
In the following issue, I asked a question：

https://github.com/dapr/docs/issues/805

**BUT：**
In the new version 0.11.2, I found that the bug is fixed only when sending multiple copies for the first time. If the pod is deleted and restarted, the above problems will occur, unless the name of deployment in YAML file is changed.

In addition, when sending messages with multiple copies, the receiver often receives more messages than its own copies. For example:

Pod A has three copies, and each copy sends a piece of data to pod B, but actually B receives more than ten or more pieces of data.

**Comment by wcs1only** [comment]
If you are still experiencing this issue on the latest version of dapr, please open an issue in the dapr/dapr project. The quickstarts queue is not as well monitored and is probably not the place for the best response times. Also, you can check out our community discord for much faster community support https://aka.ms/dapr-discord .
