### ISSUE TITLE
Observability sample needs update to reflect changes in https://github.com/dapr/dapr/issues/1317

### ISSUE THREAD

**Issue by tcnghia** [dapr/quickstarts#349]
## Expected Behavior

Observability sample shows screenshots and narrative based on current version of Dapr.

## Actual Behavior

Some screenshots like https://raw.githubusercontent.com/dapr/quickstarts/v1.0.0-rc.1/observability/img/zipkin-4.png are based on before https://github.com/dapr/dapr/issues/1317 (pre-0.7).

Also the documentations around that screenshot are wrong.

## Steps to Reproduce the Problem

Check out v1.0.0-RC.1 quickstarts

**Comment by amulyavarote** [comment]
Closing this as we have a new version of Quickstarts. Please reopen if there is more info/activity.
