### ISSUE TITLE
in statestore example: helm install redis bitnami/redis status always Pending

### ISSUE THREAD

**Issue by dybxin** [dapr/quickstarts#352]
## Ask your question here

in statestore example: helm install redis bitnami/redis status always Pending.

kubectl get pods:
```
redis-master-0                                    0/2     Pending     0          8m11s
redis-slave-0                                     0/2     Pending     0          8m11s

```

kubectl describe pods redis:

```
 Type     Reason            Age                  From               Message
  ----     ------            ----                 ----               -------
  Warning  FailedScheduling  74s (x5 over 5m43s)  default-scheduler  running "VolumeBinding" filter plugin for pod "redis-slave-0": pod has unbound immediate PersistentVolumeClaims

```

**Comment by wcs1only** [comment]
Your kubernetes cluster must have a persistent volume available for the redis containers to use. (See also: https://kubernetes.io/docs/concepts/storage/persistent-volumes/ )

Most kubernetes providers handle this automatically. May I ask which kubernetes implementation you are using to run the quickstarts on? We can update our documentation accordingly.

**Comment by wcs1only** [comment]
Also, just for the sake of unblocking you, you should be able to disable persistence:
```bash
helm install my-release --set "master.persistence.enabled=false" --set "slave.persistence.enabled=false" bitnami/redis
```
Try this and let me know if it unblocks you.

**Note: ** Never do this in production, or you may suffer data loss

**Comment by dybxin** [comment]
> Also, just for the sake of unblocking you, you should be able to disable persistence:
> 
> ```shell
> helm install redis --set "master.persistence.enabled=false" --set "slave.persistence.enabled=false" bitnami/redis
> ```
> 
> Try this and let me know if it unblocks you.
> 
> **Note:** Never do this in production, or you may suffer data loss

@wcs1only  This way Redis can be deployed successfully.

**Comment by dybxin** [comment]
@wcs1only i not use  any kubernetes providers. our company installed k8s on your own server.

**Comment by dybxin** [comment]
@wcs1only i delete redis use `helm delete redis`, then i install  redis use the following:
```bash
helm repo add bitnami https://charts.bitnami.com/bitnami
helm repo update
helm install redis --set "master.persistence.enabled=false" --set "slave.persistence.enabled=false" bitnami/redis
```
output messages:

```
[root@n1 ~]# helm install redis --set "master.persistence.enabled=false" --set "slave.persistence.enabled=false" bitnami/redis
NAME: redis
LAST DEPLOYED: Fri Dec 25 16:02:49 2020
NAMESPACE: default
STATUS: deployed
REVISION: 1
TEST SUITE: None
NOTES:
** Please be patient while the chart is being deployed **
Redis can be accessed via port 6379 on the following DNS names from within your cluster:

redis-master.default.svc.cluster.local for read/write operations
redis-slave.default.svc.cluster.local for read-only operations


To get your password run:

    export REDIS_PASSWORD=$(kubectl get secret --namespace default redis -o jsonpath="{.data.redis-password}" | base64 --decode)

To connect to your Redis server:

1. Run a Redis pod that you can use as a client:
   kubectl run --namespace default redis-client --rm --tty -i --restart='Never' \
    --env REDIS_PASSWORD=$REDIS_PASSWORD \
   --image docker.io/bitnami/redis:6.0.9-debian-10-r38 -- bash

2. Connect using the Redis CLI:
   redis-cli -h redis-master -a $REDIS_PASSWORD
   redis-cli -h redis-slave -a $REDIS_PASSWORD

To connect to your database from outside the cluster execute the following commands:

    kubectl port-forward --namespace default svc/redis-master 6379:6379 &
    redis-cli -h 127.0.0.1 -p 6379 -a $REDIS_PASSWORD

```

i use `kubectl get pods `, i not show any redis:

```
[root@n1 ~]# kubectl get pods
NAME                                              READY   STATUS      RESTARTS   AGE
details-v1-558b8b4b76-gmf74                       0/2     Error       16         136d
my-release-ingress-nginx-admission-create-8f855   0/2     Completed   2          42d
private-reg                                       0/1     Error       4250       177d
productpage-v1-6987489c74-swx4z                   2/2     Running     9          136d
ratings-v1-7dc98c7588-dtc8t                       0/2     Completed   17         136d
reviews-v1-7f99cc4496-5qb86                       2/2     Running     8          136d
reviews-v2-7d79d5bd5d-kpcbb                       0/2     Completed   17         136d
reviews-v3-7dbcdcbc56-7j6vv                       2/2     Running     9          136d
vvp-ververica-platform-7b5867b9f8-ps5r4           0/4     Pending     0          112d

```

**Comment by wcs1only** [comment]
Does it show up in?:
```bash
kubectl get pods --all-namespaces
```

As for running your own kubernetes, please understand the implications of setting up persistent volumes. If you want to

**Comment by dybxin** [comment]
@wcs1only  logs after run `kubectl get pods --all-namespaces`:

```
default                  redis-master-0                                1/1     Terminating   1          1d
default                  redis-slave-0                                 1/1     Terminating   567        1d
default                  redis-slave-1                                 1/1     Terminating   565        1d

```

**Comment by wcs1only** [comment]
From this example, it looks like your redis instances are stuck in a terminating state. Running ```kubectl describe pod redis-master-0``` might give you more information on what went wrong.

I'm going to close this issue, as running redis in a kubernetes cluster without persistent volume support is somewhat outside of the scope of the Dapr quickstarts. If you are still having trouble, could you please head on over to our community discord https://aka.ms/dapr-discord ? You'll likely be able to get much faster response times there.
