### ISSUE TITLE
Error when running Python app: exec: "flask": executable file not found in $PATH

### ISSUE THREAD

**Issue by waltermyersiii** [dapr/quickstarts#363]
## Expected Behavior

Multiply app of distributed calculator fails to run from command: dapr run --app-id multiplyapp --app-port 5000 --dapr-http-port 3501 flask run

## Actual Behavior

Get this error: exec: "flask": executable file not found in $PATH

## Steps to Reproduce the Problem

I'm using VS Code with WSL2 Ubuntu 20.04. Dapr CLI/Runtime: 0.11.0/0.11.3

**Comment by wcs1only** [comment]
When you run (from step 4):
```bash
pip3 install wheel python-dotenv flask_cors flask
``` 

Did you get any errors? If you got a warning like this:
```bash
WARNING: The script flask is installed in '/home/charlie/.local/bin' which is not on PATH.
```

You'll need to do something like the following:
```bash
export PATH=$PATH:$HOME/.local/bin
```

**Comment by gregfiske** [comment]
Step 4 of the "v1-rc2" version of the readme (https://github.com/dapr/quickstarts/blob/v1.0.0-rc.2/distributed-calculator/README.md) doesn't mention installing flask. It just says: 
```
pip3 install wheel
pip3 install python-dotenv

**Comment by wcs1only** [comment]
Ah ok. This has been fixed already in the master branch. The next release will have the correct steps: https://github.com/dapr/quickstarts/blob/master/distributed-calculator/README.md
