### ISSUE TITLE
PR's being rejected due to invalid ubuntu tests

### ISSUE THREAD

**Issue by yoDon** [dapr/quickstarts#369]
## Expected Behavior

Trivial documentation tweak PR's like https://github.com/dapr/quickstarts/pull/368 should pass cross-platform validation tests

## Actual Behavior

The Ubuntu bindings are throwing errors blocking trivial PRs when there is no visible difference in the test outputs (CR/LF or Tab/Space mismatches?)

Sample output (from automated validation of https://github.com/dapr/quickstarts/pull/368 which is a trivial documentation-only PR)

```
Step: Run kubernetes apps
	Expected stdout:
		component.dapr.io/sample-topic created
		service/bindings-nodeapp created
		deployment.apps/bindings-nodeapp created
		deployment.apps/bindings-pythonapp created
	Actual stdout:
	ERROR expected lines not found:
		component.dapr.io/sample-topic created
		service/bindings-nodeapp created
		deployment.apps/bindings-nodeapp created
		deployment.apps/bindings-pythonapp created
	Expected stderr:
	Actual stderr:
Step: Read Python Logs
	Expected stdout:
		{'data': {'orderId': 10}, 'operation': 'create'}
		<Response [204]>
		{'data': {'orderId': 11}, 'operation': 'create'}
		<Response [204]>
	Actual stdout:
	ERROR expected lines not found:
		{'data': {'orderId': 10}, 'operation': 'create'}
		<Response [204]>
		{'data': {'orderId': 11}, 'operation': 'create'}
		<Response [204]>
	Expected stderr:
	Actual stderr:
Step: Read Node Logs
	Expected stdout:
		Hello from Kafka!
		{ orderId: 10 }
		Hello from Kafka!
		{ orderId: 11 }
	Actual stdout:
	ERROR expected lines not found:
		Hello from Kafka!
		{ orderId: 10 }
		Hello from Kafka!
		{ orderId: 11 }
	Expected stderr:
	Actual stderr:
```

## Steps to Reproduce the Problem

Submit trivial PR, wait for automated validation of PR

**Comment by yoDon** [comment]
This issue is also causing another doc-only PR to be rejected https://github.com/dapr/quickstarts/pull/371

**Comment by yoDon** [comment]
Is it possible someone fixed this on your end (an equally trivial PR #373 just succeeded), and if so how do I re-trigger the failed checks to run on the PR's I submitted where the ubuntu bindings tests failed?

**Comment by wcs1only** [comment]
Thanks for bringing this up. The output of interest is just above what you pasted:
```bash
helm install dapr-kafka bitnami/kafka --wait --namespace kafka -f ./kafka-non-persistence.yaml`
	return_code: -15
	Expected stdout:
	Actual stdout:
		"bitnami" already exists with the same configuration, skipping
		Hang tight while we grab the latest from your chart repositories...
		...Successfully got an update from the "bitnami" chart repository
		Update Complete. ⎈Happy Helming!⎈
		namespace/kafka created
		
	Expected stderr:
	Actual stderr:
```

The ```return_code: 15``` indicates that the helm install of dapr-kafka was timing out and being killed. The kafka helm chart is a little slow, so I'll update the timeout from its default of 60s.
