### ISSUE TITLE
Broken link in Hello-World quickstart

### ISSUE THREAD

**Issue by pcracknell** [dapr/quickstarts#379]
## Expected Behavior

In Step 1:
"Follow instructions to download and install the Dapr CLI and initialize Dapr."
The instructions to link to a valid URL

## Actual Behavior

404

## Steps to Reproduce the Problem

Click the link

**Comment by wcs1only** [comment]
You are referring to the link on this line: https://github.com/dapr/quickstarts/blame/9138a8ecd499afca0552b26eb513fec5cc3669f9/hello-world/README.md#L20 correct? It seems to be working correctly for me:

```
curl -I https://docs.dapr.io/getting-started/install-dapr/
HTTP/2 200 
cache-control: must-revalidate, max-age=30
content-length: 373
content-type: text/html
accept-ranges: bytes
etag: "05716900"
strict-transport-security: max-age=10886400; includeSubDomains; preload
referrer-policy: same-origin
x-content-type-options: nosniff
x-xss-protection: 1; mode=block
x-dns-prefetch-control: off
date: Tue, 16 Feb 2021 22:15:19 GMT
```

Can you please confirm?

**Comment by wcs1only** [comment]
I have enabled automatic broken link detection via: #397 and #387. This should help us catch any broken links going forward.
