### ISSUE TITLE
When invoking new order in hello-world: "errorCode": "ERR_DIRECT_INVOKE",     "message": "invoke API is not ready"

### ISSUE THREAD

**Issue by gary-desroches** [dapr/quickstarts#388]
## Expected Behavior

== APP == Got a new order! Order ID: 42
== APP == Successfully persisted state.

## Actual Behavior

"errorCode": "ERR_DIRECT_INVOKE",
    "message": "invoke API is not ready"

## Steps to Reproduce the Problem

Follow the instructions on Windows 10 to install and init dapper 1.0.0 in Docker, then cloning and running the hello-world app on your local machine.  Get to the point where you POST a new order with the following URL and body data.

http://localhost:3500/v1.0/invoke/nodeapp/method/neworder

```
{
  "data": {
    "orderId": "42"
  } 
}
```

**Comment by Edward-Roshan** [comment]
Indeed. I got same issue. And dapr runtime looks like a proxy. every time I invoke back application. I need go through dapr api. is there any way to expose port directly from back to dapr placement?

**Comment by seanfitzg** [comment]
I'm getting a similar error.  I've created a .net core demo application at https://github.com/seanfitzg/HomeCookingApi.  
Started with:
`dapr run --app-id recipe-app --app-port 80 dotnet run`

Which logs:
`http server is running on port 54320" app_id=recipe-app instance=LAPTOP-IPMCMFH9 scope=dapr.runtime type=log ver=1.0.1`

And calling:
`curl http://localhost:54320/v1.0/invoke/recipe-app/method/recipes `

Returns:
`{"errorCode":"ERR_DIRECT_INVOKE","message":"invoke API is not ready"}`

**Comment by sjf10050** [comment]
`npm install express --save`
the app.js require module '[express](https://expressjs.com/)'

**Comment by wcs1only** [comment]
So, we regularly validate our quickstarts in Windows, and I am able to run this one without issue on a Windows 10 machine. Dapr relies on mDNS for service discovery while running locally. We have received reports of users having trouble when certain security/firewall/VPN software blocks access to mDNS. Are you running any firewalls/VPN configuration on your machine?

**Comment by seanfitzg** [comment]
> I'm getting a similar error on windows 10. I've created a .net core demo application at https://github.com/seanfitzg/HomeCookingApi.
> 
> Started with:
> `dapr run --app-id recipe-app --app-port 80 --dapr-http-port 3500 dotnet run`
> 
> Running:
> `curl http://localhost:3500/v1.0/invoke/recipe-app/method/recipes `
> 
> Returns:
> `{"errorCode":"ERR_DIRECT_INVOKE","message":"invoke API is not ready"}`
> 
> I wonder if there is an issue with .net core invocation on Win10. I don't think I'm doing anything wrong.

fyi, I figured out my issue: https://github.com/dapr/dapr/issues/2954#issuecomment-824941812

**Comment by wcs1only** [comment]
Ah, glad you were able to sort this out. We've also made some changes to the way `dapr run` works in v1.2 that should make it a little more obvious that daprd has failed with an error.
