### ISSUE TITLE
Tracing(Observability ) is not working as expected. 

### ISSUE THREAD

**Issue by RevathiNeminathan** [dapr/quickstarts#391]
## Expected Behavior

I expected to see tracing information when ever new request comes to the API. 
I have taken subtract api from distributed-calculator and ran below command.
dapr run --app-id hello-tracing --app-port 5100 -- dotnet  Subtract.dll

zipkin dispalyed trace details only once but I expected to see trace details for every request also I don't see data field in zipkin UI.

![zipkin](https://user-images.githubusercontent.com/36435194/108355056-51a8eb00-7210-11eb-8b18-d24ba296b64e.PNG)

Note:
I can see trace details of each request if I use curl command but same not happening with postman

## Steps to Reproduce the Problem

1. Copy csharp folder from distributed-calculator
2. build the  Subtract.csproj using dotnet build command /vscode/visual studio
3. run below command
dapr run --app-id hello-tracing --app-port 5100 -- dotnet  Subtract.dll
4. make post request using postman

**Comment by wcs1only** [comment]
When you say, make the request using postman, are you invoking the dotnet app directly and not through Dapr? Dapr adds appropriate trace headers, but it cannot do so if you are bypassing it entirely and are just making requests to the app directly.

Please see https://docs.dapr.io/concepts/observability-concept/ for more information.

Also, for questions like this, you're more likely to get a speedy answer on our community discord: https://aka.ms/dapr-discord
