### ISSUE TITLE
"Hello Kubernetes" -- How to use Helm (for a non-`default` namespace)

### ISSUE THREAD

**Issue by DazWilkin** [dapr/quickstarts#393]
Interested to explore dapr on Kubernetes but hit a roadblock immediately:

https://github.com/dapr/quickstarts/blob/master/hello-kubernetes/README.md

I prefer not to pollute `default` and like to treat namespaces like projects and be able to delete them once done.

The [README](https://github.com/dapr/quickstarts/blob/master/hello-kubernetes/README.md) says: "Please note, that using the CLI does not support non-default namespaces. If you need a non-default namespace, Helm has to be used (see below)." but I was unable to quickly find the Helm chart.

Should the README reference this set of [instructions](https://github.com/dapr/dapr/tree/master/charts/dapr)?

**Comment by wcs1only** [comment]
Actually, the README is just wrong, the CLI supports specifying a namespace using the ```-n <namespace>``` option. Thanks for spotting this, I'll fix the README
