### ISSUE TITLE
PR's being rejected due to invalid ubuntu tests (again)

### ISSUE THREAD

**Issue by yoDon** [dapr/quickstarts#396]
## Expected Behavior

1) Trivial PR's that succeed on other platforms and that return expected results on ubuntu should succeed on Ubuntu.

2) Success or failure on test cases should be deterministic

## Actual Behavior

The Ubuntu bindings are throwing errors blocking trivial PRs when there is no visible difference in the test outputs. This is likely the same helm timing issue @wcs1only reported as fixed when closing a [similar issue]( https://github.com/dapr/quickstarts/issues/369).

## Steps to Reproduce the Problem

See for example https://github.com/dapr/quickstarts/pull/373

**Comment by wcs1only** [comment]
https://github.com/dapr/quickstarts/runs/1922908132 <- This looks like the particular failure associated with #373 that you are reporting? There was some non-determinism in our distributed-calculator curl test output. I actually fixed this one as part of #387 because I was hitting it there too.
