### ISSUE TITLE
Multiple race conditions when deploying quickstarts to Kubernetes

### ISSUE THREAD

**Issue by yoDon** [dapr/quickstarts#398]
## Expected Behavior

Quickstarts should work reliably without needing users to unintentionally pause for long enough between steps to avoid hidden race conditions,

## Actual Behavior

Quickstarts are all subject to race conditions if their steps are performed quickly and sequentially without human pauses between steps.

## Steps to Reproduce the Problem

See the [issue](https://github.com/dapr/dapr/issues/2861) I posed in the main dapr repo documenting three race conditions in the hello-kubernetes quickstart. 

Until there is a dapr CLI solution to this issue, I think the race conditions should be called out in the quickstarts (the more comfortable I became with the quickstarts, the faster I ran through them, and the more unreliable and unpredictable they became).

**Comment by wcs1only** [comment]
So there is a complexity tradeoff here. Kubernetes already supports waiting for operations to complete:

https://kubernetes.io/docs/reference/generated/kubectl/kubectl-commands#wait

We could add ```kubectl wait``` commands after all of our kubectl operations, but that's going to add a lot of additional steps which we then have to explain to beginners. I'm not opposed to doing this, but we have to think carefully about the complexity tradeoff of having to explain to beginners exactly why these waits are necessary. In the example you gave in the other ticket, the sleeps you inserted were <12s. A first time user who is reading the quickstarts and executing the steps isn't very likely to be executing steps faster than this and we have to weigh this against the potential confusion they might experience by increasing the complexity of the document itself.

When you are running into these races, are you executing these steps as a new user would? Or is it that you are trying to build your own deployment automation based on the quickstart examples, and you've run into these races and you are looking for a cleaner solution than just sleeping? Would adding a general note about building automation using ```kubectl wait``` be enough to clear this up for your use case?

**Comment by yoDon** [comment]
@wcs1only I'm exactly the beginner you're talking about, having never touched Kubernetes before trying to learn Dapr. I get that these strategic decisions on how to aim docs are hard, so I'll try to paint a picture of my journey in case it's helpful...

When I started trying to learn Dapr, the first couple quickstarts I tried were awesome and worked perfectly and I felt excited and empowered by this amazing set of tools. Then as I got the hang of things I naturally started both going faster and trying to make my own toy projects, at which point everything started getting sketchy and unreliable. Confused, I went back to first principles and started going through things I'd done successfully in the past like the original hello-kubernetes quickstart. All of a sudden this dapr project I'd been falling in love with was completely sketchy and unreliable and only worked a fraction of the time. I chalked up this buggy behavior as the realities of first release software and dug in to start finding solid repros to file bug reports on. A dozen or so hours later, almost all of which spent puzzling through kubernetes and starting to learn how it works, I realized that dapr had become buggy and unreliable just as I became comfortable with it because of all these hidden undocumented race conditions I was having to find one by one on my own (while also having to learn the skills to find how to find where and why they were happening).

The need for delays or wait statements when using kubernetes is clearly real. The importance of instantiation order in kubernetes is clearly real. Leaving out any mention of it from your docs because it's "hard" doesn't help your new-to-kubernetes users, it just makes it impossible for them to succeed with anything real. Just knowing race conditions and intitiation order issues were potentially a thing would have save me hours of bug searching and given me a lot more confidence in the reliability of dapr (which was looking pretty sketchy there for a while). Also, for at least the next couple years anyone who is going to even consider using dapr is going to be more than experienced enough to understand wait statements and initiation order constraints, particularly if you spend just a couple words explaining why they are there. My recommendation is to be honest with your users about the complexity that is present, because it is there and they will encounter it.

**Comment by wcs1only** [comment]
Thanks, that's good feedback. I think it is clear from your feedback that we need to deal with the asynchronous nature of kubernetes deploys in a manner that is more clear to the beginner. Let me take a crack at it for hello-kubernetes and see what we come up with.

**Comment by wcs1only** [comment]
@yoDon can you run hello-kubernetes from #403 and see if it clears things up for you?

**Comment by yoDon** [comment]
@orizohar The PR you referenced does NOT close this issue. 

The changes @wcs1only are insufficient to prevent the race conditions users will encounter as described above, both in terms of not preventing race conditions in the one specific quickstart his PR touched (there is another major race condition following the initial `dapr init -k` which if followed too quickly by a `kubectl apply -f something` results in damaged daprd containers) and in terms of not doing any prevention or discussion of the more complex race conditions present in the other tutorials. Users will hit these race conditions and Dapr will appear to be buggy and unreliable as a result, again as described above.

Unless the goal is to sweep issues under the rug to keep the issue count low, this issue needs to be re-opened and resolved correctly.

**Comment by orizohar** [comment]
Reopening. @yoDon - my apologies, I saw the mention of the issue in the PR and was under the impression it addressed it. @wcs1only - since you started looking at this, can you address the gaps that still exist?

**Comment by wcs1only** [comment]
Yes, I was going to follow up with a pass through our other kubernetes quickstarts. I just created that PR to get some quick feedback from @yoDon if that approach sufficiently addressed the races they encountered in the hello-kubernetes quickstart.

**Comment by yoDon** [comment]
@wcs1only I found I needed to do a `kubectl wait --for=condition=ready pod --namespace dapr-system --all --timeout=120s` after the initial `dapr init -k`. I'm also doing an `kubectl wait --for=condition=ready pod --all --timeout=120s` after helm installing ingress-nginx and again the last of my `kubectl apply -f` lines (not all in the hello-kubernetes case, obviously, but in the more general case).
