### ISSUE TITLE
Difference between bindings and publish&subscribe?

### ISSUE THREAD

**Issue by bryht** [dapr/quickstarts#404]
For me it seems like input binding is same with subscribe, and output binding is same with publish?
Can anyone help me to understand their radical difference?

**Comment by wcs1only** [comment]
In general, pub-sub is for dapr-to-dapr communication. Bindings are for integration with external services. 

Also, FYI: we have a discord server that will probably get you a much quicker response to that kind of question:

https://aka.ms/dapr-discord

**Comment by adeliab** [comment]
what if i want to have an .net core API that listens to a service bus topic subscription? the messages in this topic comes from an external system. which component should I use and is there a code example for it?
i also don't want dapr to create the subscription but listens to an existing one
