### ISSUE TITLE
Mention Dashboard in quickstarts

### ISSUE THREAD

**Issue by artursouza** [dapr/quickstarts#438]
## Describe the proposal

Hello World and Hello Kubernetes quickstarts should include using the Dapr Dashboard. Right now, there is no instructions encouraging users to try the Dapr Dashboard.

Add it as an optional step in one of the quickstarts. Do not include the Dashboard screenshots and experience, just a reference.

**Comment by robsondepaula** [comment]
Hello @artursouza, could you please review the PR with a proposal?
