### ISSUE TITLE
Observability quickstart autovalidation periodically fails.

### ISSUE THREAD

**Issue by wcs1only** [dapr/quickstarts#445]
## Expected Behavior

Should always pass. I suspect that we introduced a timing issue with https://github.com/dapr/quickstarts/pull/427/files#diff-90e295cf1374b2edc4a2d2bbfc9e9c3e1ead9461d21177fcac8b8ebdf59b5cacR49

## Actual Behavior

Intermittent failure.

https://github.com/dapr/quickstarts/runs/2841465510?check_suite_focus=true#step:13:48

## Steps to Reproduce the Problem

Run the github action enough times.

**Comment by paulyuk** [comment]
I've been watching failures and I don't see this one in past several months.  Please reopen if coming up.
