### ISSUE TITLE
Proposal: refactor Hello-World quickstart into /node and /python subfolders

### ISSUE THREAD

**Issue by paulyuk** [dapr/quickstarts#477]
Today, the /hello-world quickstart is a "flat folder" that contains Node.js files (app.js) and Python files (app.py) in the same folder. This makes devops a pain, e.g. building clean or writing a single Dockerfile for each of the services.

## Describe the proposal
The proposal is to lightly refactor the node.js code into \node and python code into \python subfolders.  The README will need to be updated guiding the dev to build and run those services out of those folders.

The benefits are:
- separation of services and concerns (like distributed calculator or any other microservice repo)
- repo / environment realism
- ability to create unique devops assets like Dockerfiles or GH actions for each folder

I will be happy to make the PR.

**Comment by msfussell** [comment]
This makes sense to me. Many of the other quickstart are also factored like this (e.g. pub/sub), so it would be better to apply this to all of them. If not, then this only actually applies to those where you want to include the dockerfiles, which are the quickstart deployed to K8s.

**Comment by paulyuk** [comment]
> This makes sense to me. Many of the other quickstart are also factored like this (e.g. pub/sub), so it would be better to apply this to all of them. If not, then this only actually applies to those where you want to include the dockerfiles, which are the quickstart deployed to K8s.

Makes sense @msfussell .  I will volunteer to do all of them.  However as not to make an epic size PR, how about I just put ./hello-world through review first?

**Comment by paulyuk** [comment]
@msfussell  PR is submitted. #478

**Comment by msfussell** [comment]
Actually I looked at the PR and realize that I did not look at this closely enough and though this was just adding folders for the apps to be consistent. Adding dockerfiles to the hello world quickstart is not needed, only in the K8s version where you have to have containers.

**Comment by paulyuk** [comment]
@msfussell ok I agree it makes sense to split out deployment matters including docker into separate folders and work.  I revised PR based on this feedback.
