### ISSUE TITLE
Hello-Kubernetes bug in step 4

### ISSUE THREAD

**Issue by jgardner04** [dapr/quickstarts#480]
## Expected Behavior

When running the below command into the app, I expect an order to be submitted. 
`curl --request POST --data @sample.json --header Content-Type:application/json http://localhost:8080/neworder
`

## Actual Behavior

The curl command returns an error below: 

```
❯ curl --request POST --data @sample.json --header Content-Type:application/json http://localhost:8080/neworder
ParserError:
Line |
   1 |  curl --request POST --data @sample.json --header Content-Type:applica …
     |                             ~~~~~~~
     | The splatting operator '@' cannot be used to reference variables in an expression. '@sample' can be used only as an argument to a command. To reference variables in an expression use '$sample'.
```

## Steps to Reproduce the Problem

I am running the command using the following configuration.
Windows 10
Powershell 7.1.4

I just copied the line from the website after confirming that the curl output was correct for the port.

## I have a fix and will submit a PR shortly

**Comment by msfussell** [comment]
I think the issue here is that linux command line will let this through with no quotes. Nevertheless this should be fixed.

**Comment by jgardner04** [comment]
@msfussell this is a good point. I just confirmed that the updated command will work on Linux (Ubuntu on WSL) as well as Win.
