### ISSUE TITLE
bump devcontainer image version

### ISSUE THREAD

**Issue by spottedmahn** [dapr/quickstarts#498]
I had an issue running the quickstarts in a devcontainer: https://github.com/microsoft/vscode-dev-containers/issues/1192

[There's a fix](https://github.com/microsoft/vscode-remote-release/issues/5949#issuecomment-984146373) coming in 1.6.9 🎉

>Note that the sample's version number will need to be bumped up in the Dockerfile. That one is actually fairly old. 1.4.0 is from May 25th. This would be 1.6.3 once released.
reference: https://github.com/microsoft/vscode-remote-release/issues/5949#issuecomment-984146373

can the image version number get bumped?  thanks!  (happy to submit a PR 😉)

**Comment by wcs1only** [comment]
Would love a PR for this.
