### ISSUE TITLE
where's the "Open with Codespaces" option?

### ISSUE THREAD

**Issue by spottedmahn** [dapr/quickstarts#501]
>If you would like to jump in right away by using GitHub Codespaces, you can click on "Code" in this repo and "Open with Codespaces"
[source](https://github.com/dapr/quickstarts#:~:text=if%20you%20would%20like%20to%20jump%20in%20right%20away%20by%20using%20github%20codespaces%2C%20you%20can%20click%20on%20%22code%22%20in%20this%20repo%20and%20%22open%20with%20codespaces%22)

I assume the "you can click on 'Code' in this repo" is this button, right?  I don't see that option? 🤔

![image](https://user-images.githubusercontent.com/14079228/145045633-edf6fde0-df4f-4a2b-b9bf-079e0ed2b52a.png)

**Comment by paulyuk** [comment]
Hey @spottedmahn, currently you need a level of GitHub subscription for this feature to show up.  I believe that is GitHub Team or GitHub Enterprise Cloud.  More here: https://docs.github.com/en/codespaces/getting-started/quickstart

There is a way to load the quickstarts in DevContainers on your local machine so long as you have Docker, VS Code, and VS Remote Container extension.  This is a similar experience, just running in containers on your own machine vs. fully in the cloud.  hope that helps. https://code.visualstudio.com/docs/remote/containers

**Comment by spottedmahn** [comment]
>currently you need a level of GitHub subscription for this feature to show up

that makes sense.  perhaps the _readme.md_ should be updated then? 🤔

I'm happy to submit a PR for that 😉

**Comment by paulyuk** [comment]
> > currently you need a level of GitHub subscription for this feature to show up
> 
> that makes sense. perhaps the _readme.md_ should be updated then? 🤔
> 
> I'm happy to submit a PR for that 😉

That's a good idea @spottedmahn, thank you.

**Comment by paulyuk** [comment]
I believe this is fixed based on your feedback

**Comment by spottedmahn** [comment]
yep, looks great, thanks!

![image](https://user-images.githubusercontent.com/14079228/155721712-0cbe5d6b-4ed9-48b2-9053-91a40034a429.png)
