### ISSUE TITLE
dapr does not recognize running apps

### ISSUE THREAD

**Issue by ozzy92** [dapr/quickstarts#503]
Following the instructions in hello-world readme, I'm able to run both the node and python apps, but the dashboard shows no apps, and dapr list says "No Dapr instances found."

The dapr command to post an order reports: "error invoking app nodeapp: app ID nodeapp not found."

The command windows show both apps running, I can post and get using curl and postman and (get) with browser.
Running Dapr 1.50.1. Windows 10 with Docker Desktop.  I see the containers running in Docker.
Stumped on why dapr commands don't recognize the apps running, when they are obviously running.

**Comment by paulyuk** [comment]
Hi @ozzy92 

Sorry to hear this.  I'm guessing answer is yes but just in case when you run the app you're doing the `dapr run ..` right?  The symptom you describe can happen when you use daprd or VS tools based on daprd.  

If you're on a Mac sometimes this content filter can cause this issue: 
https://docs.dapr.io/operations/troubleshooting/common_issues/#service-invocation-is-failing-and-my-dapr-service-is-missing-an-appid-macos

If that doesn't work I might suggest reinstalling the dapr runtime.  That's pretty fast and easy doing this:
`dapr uninstall --all`
`dapr init`

Then try the `dapr run` .. again.  Please let me know.
