### ISSUE TITLE
 Failed to provision revision for container app 'xxxxx'. Error details: Code: 90715, ExtendedCode: 90715, Message: Error provisioning container app due to invalid Dapr configuration. Please check the dapr configuration and validate if all secrets are configured correctly.

### ISSUE THREAD

**Issue by SarangRapid** [dapr/quickstarts#506]
when trying to provision app through powershell, with following YAML component for dapr, same thing happened through portal.
Same configuration is running fine on local machine

- name: statestore
  type: state.azure.tablestorage
  version: v1
  metadata:
  - name: accountName
    value: xxxxacc
  - name: accountKey
    value: <key>
  - name: tableName
    value: statemanagement

**Comment by SarangRapid** [comment]
its been resolved, I was using Dapr in dot net core 6 which comes with DaprClient listens default on 50001 port, and that was the thing which I misconfigured, I will check how to set listening port as an configurable variable

**Comment by wcs1only** [comment]
Glad you got this resolved. I'm going to go ahead and close this issue, since it does not appear to be a problem with the quickstarts specifically. 

If you are still having trouble, I recommend heading over to our community discord channel:
https://aka.ms/dapr-discord
