### ISSUE TITLE
pub-sub react-form quickstart throws error on startup when getting subscriptions

### ISSUE THREAD

**Issue by AaronCrawfis** [dapr/quickstarts#516]
## Expected Behavior

Dapr sidecar should initialize without errors

## Actual Behavior

```
> dapr run --app-id react-form --app-port 8080 npm run start
time="2022-01-18T17:13:43.5832117-08:00" level=error msg="error getting topics from app: invalid character '<' looking for beginning of value" app_id=react-form scope=dapr.runtime type=log ver=1.5.1
time="2022-01-18T17:13:43.5845395-08:00" level=error msg="error occurred while beginning pubsub pubsub: error getting topics from app: invalid character '<' looking for beginning of value" app_id=react-form scope=dapr.runtime type=log ver=1.5.1
```

## Steps to Reproduce the Problem

Follow pub-sub quickstart steps for local or Kubernetes

## Underlying issue

`server.js` returns index.html upon any request that isn't `/publish`: https://github.com/dapr/quickstarts/blob/9978080e0607c91e58233f3b54f7921dd53a7eaa/pub-sub/react-form/server.js#L30

This returns the index.html file and causes Dapr to throw an error when initializing

**Comment by paulyuk** [comment]
Thank you Aaron, I'll submit a fix.
