### ISSUE TITLE
distributed-calculator - upgrade to .NET 6

### ISSUE THREAD

**Issue by marcinjahn** [dapr/quickstarts#544]
## Describe the proposal

I think it would be great to have the csharp app part of the distributed-calculator quickstart to be upgraded to .NET 6. Possibly, the app should also make use of the Minimal APIs, which would make the code much shorter (especially considering how simple that app is).

**I'd be happy to create a PR with that** if you think it's a good idea :)

**Comment by paulyuk** [comment]
Hey Marcin - I  personally like this direction.  This is what we are doing in the revamped quickstarts that are more API by API.  Please see this one as an example of .NET 6 minimal API + Dapr: https://github.com/dapr/quickstarts/tree/feature/new_quickstarts/pub_sub/csharp

Let's check with our maintainer @msfussell what he wants.

**Comment by msfussell** [comment]
@marcinjahn - Hopefully as @paulyuk says the new service invocation quickstarts cover this now. Take a look. There is only on C# app in the Dist calc and so I would suggest leaving as is for now.
