### ISSUE TITLE
New Quickstarts: Add a section on Configuration API

### ISSUE THREAD

**Issue by tanvigour** [dapr/quickstarts#554]

**Comment by akhilac1** [comment]
@amulyavarote - configuration build block is planned for usage in customer scenarios and it would be good to have a basic Quickstart with HTTP and gRPC API. Can we please re-open this issue?

@sarsharma @rabollin

**Comment by amulyavarote** [comment]
@akhilac1 This issue is open only. I closed a duplicate issue which is issue number #496

**Comment by amulyavarote** [comment]
Hi @sarsharma, Any update on this task?

**Comment by sarsharma** [comment]
Hey @amulyavarote, I have started working on it.

**Comment by msfussell** [comment]
Configuration API is complete
