### ISSUE TITLE
Dependency review nth-check

### ISSUE THREAD

**Issue by paulyuk** [dapr/quickstarts#556]
Please review nth-check dependency.

The latest possible version that can be installed is 1.0.2 because of the following conflicting dependency:

react-scripts@5.0.0 requires nth-check@^1.0.2 via a transitive dependency on css-select@2.1.0
The earliest fixed version is 2.0.1.

**Comment by shubham1172** [comment]
https://github.com/facebook/create-react-app/issues/12055

**Comment by amulyavarote** [comment]
@paulyuk Can you please provide more details on this? What change is needed here?

**Comment by MACEL94** [comment]
Hi

my PR #763 fixes this dependabot security warning.
I solved it the same way i did for another project of mine.

I hope the PR can help you close this down @paulyuk @shubham1172 @amulyavarote @greenie-msft @tanvigour.
