### ISSUE TITLE
Change this build pipeline to login to GHCR and re-enable PR validation

### ISSUE THREAD

**Issue by tanvigour** [dapr/quickstarts#568]

**Comment by paulyuk** [comment]
Hi @tanvigour, here is a suggested plan that will fix up the issue and stabilize the pipeline.  We will basically 100% remove the docker hub dependency in our build and test workflows.  We will start pushing to GHCR on build, and our tests will pull from there.  Also community images will *separately* be cached and pushed to this GHCR; this is not something we should do all the time but rather about once a month (it's an expensive operation and doesn't change much - so poor ROI).  let's use a convention like `/dapr/samples` to store these in the container registry.

1. Build.yaml workflow will now only login to GHCR and Publish samples containers to GHCR. There will be NO docker hub dependency in this anymore.
2. Kubernetes manifests will be updated to start pulling samples containers from GHCR to match #1 
3. A new Cache.yaml workflow will be created that signs into Docker hub, pulls down the kafka and zookeper community images, logs out of Docker Hub, logs into GHCR, and retags and pushes these two cached images to GHCR in a /dapr/samples registry. This should only be triggered about 1/mo, and we can manually trigger initially.
4. kafka.yml file used by bindings will be updated to pull `kafka` and `zookeeper` from GHCR to match #3


Each unit above should test ok before moving to next..

**Comment by artursouza** [comment]
I think the Cache.yaml pipeline to cache 3rd party images into out GHCR registry should be done in dapr/dapr since we can use that for many other 3rd party images, even those used in CLI (zipkin, for example).
