### ISSUE TITLE
hello-kubernetes/deploy/redis.yaml seems not getting properly the Redis password from the secret

### ISSUE THREAD

**Issue by simone-zennaro** [dapr/quickstarts#586]
## Involved code snippet:

`  - name: redisPassword
    secretKeyRef:
      name: redis
      key: redis-password
auth:
  secretStore: kubernetes`

## Workaround: 
replace secretKeyRef with the (base64 decoded) Redis secret and remove (or comment) auth and secretstore lines:
`  - name: redisHost
    value: redis-master:6379
  - name: redisPassword
    value: O4FVn8CmA8`

**Comment by ben790924** [comment]
Thanks for your infomation
