### ISSUE TITLE
distributed-calculator pods Crash in k3s

### ISSUE THREAD

**Issue by lemchen** [dapr/quickstarts#644]
Fllowing the tutorial, some pods crash

$kubectl get pods

addapp-75f74c8649-pbbml                 0/2     ContainerCreating   0              8m47s
svclb-calculator-front-end-gfj6m        0/1     Pending             0              8m47s
svclb-calculator-front-end-8kdmc        0/1     Pending             0              8m47s
svclb-calculator-front-end-q22fd        0/1     Pending             0              8m47s
svclb-calculator-front-end-nzcz2        0/1     Pending             0              8m47s
svclb-calculator-front-end-c2r5v        0/1     Pending             0              8m47s
divideapp-8645c46dbc-lzphj              2/2     Running             0              8m47s
calculator-front-end-59cbb6658c-cwwbv   2/2     Running             0              8m47s
multiplyapp-6459697c46-bszfq            1/2     CrashLoopBackOff    7 (107s ago)   8m47s
subtractapp-58645db87-z95xj             1/2     CrashLoopBackOff    7 (95s ago)    8m47s

btw, i'm running k3s cluster instead k8s. other tutorial is normal.

**Comment by artursouza** [comment]
We test our QuickStarts on K3s on Raspberry Pis on every release.

In order to help with this issue, could you do a kubectl describe on the crashing PODs?

**Comment by paulyuk** [comment]
Although we do build for ARM: 
<img width="663" alt="image" src="https://user-images.githubusercontent.com/1968137/163225648-e6827e66-39fc-4267-81e4-dce50b5fc11e.png">

**Comment by lemchen** [comment]
thanks @paulyuk and @artursouza , i found the answer. it seems to something wrong with k3s.
