### ISSUE TITLE
Old workflow runs clutter up the Actions pane

### ISSUE THREAD

**Issue by paulyuk** [dapr/quickstarts#646]
Today we have old workflow runs 27+ days old that all have the same "autovalidate .." name and clutter up the window.

Could we please delete the old runs to clean this up?

This post seems to be the community favorite solution to bulk delete runs from a given workflow:
https://stackoverflow.com/questions/57927115/anyone-know-a-way-to-delete-a-workflow-from-github-actions/65374631#65374631

**Comment by paulyuk** [comment]
Visual from: https://github.com/dapr/quickstarts/actions

<img width="431" alt="image" src="https://user-images.githubusercontent.com/1968137/163056447-e1a7c80d-c219-44e1-9e87-07a674994d97.png">

**Comment by paulyuk** [comment]
@amulyavarote

**Comment by amulyavarote** [comment]
@paulyuk Should we disable all the old workflows?

**Comment by paulyuk** [comment]
@amulyavarote yes, check it out.  If you like, let's call this Resolved.

![image](https://user-images.githubusercontent.com/1968137/193124345-2b0b4db1-7b48-41aa-ac91-b085a3379651.png)

**Comment by amulyavarote** [comment]
Looks good to me! Closing this issue.
