### ISSUE TITLE
Quickstarts examples for secrets management

### ISSUE THREAD

**Issue by amulyavarote** [dapr/quickstarts#652]
## Describe the feature

Add quickstarts examples for secrets management in three languages. 

- Csharp
- Javascript
- Python

Feature Description:

There is an order-processor service which will fetch secret from the local secret store. 

**Component:**

apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: localsecretstore
  namespace: default
spec:
  type: secretstores.local.file
  version: v1
  metadata:
  - name: secretsFile
    value: secrets.json
  - name: nestedSeparator
    value: ":"

**secrets.json**
{
    "secret": "Order processor pass key"
}

**Comment by msfussell** [comment]
The discussion here is whether to use the file secret store or the Env Vars secrets store in the example. The latter is more geared to being used in a CI/CD pipeline such as GH Actions.
