### ISSUE TITLE
Dapr Go Pub Sub Quick Start - Doc update and graceful shutdown

### ISSUE THREAD

**Issue by akhilac1** [dapr/quickstarts#656]
## Expected Behavior

Commands to start the order-processor app should work and user should be able to see the "Subscriber received" messages when the quick start is setup as per documented instructions.

## Actual Behavior
The subscriber exhibits two different behaviours : 
- Subscriber does not receive the messages published
- Subscriber startup fails since port is in use

- In order-processor, the startup port is defined as ':6001' in app.go, while the documentation shows 6002 as the app-port. 
- When the order-processor is stopped using dapr command 'dapr stop order-processor' after leaving it idle for a few minutes, the app is not closed.
## Steps to Reproduce the Problem

- Follow the steps in the quickstart - https://docs.dapr.io/getting-started/quickstarts/pubsub-quickstart/
- Wait for the expected output from subscriber
- dapr stop order-processor 
- Change the command to start the order processor to 
dapr run --app-port 6001 --app-id order-processor --app-protocol http --dapr-http-port 3501 --components-path ../../../components -- go run app.go

**- Replicating the Hanging port issue**
- Run the setup multiple times followed by clean up via dapr stop. 
- Random occurrence of hanging port can be verified by checking with 'sudo lsof -i:6001'

Also see https://github.com/dapr/docs/pull/2369#discussion_r851557412 where the http and SDK ports are different and hence the docs are wrong.

**Comment by msfussell** [comment]
Also see https://github.com/dapr/docs/pull/2369#discussion_r851557412 where the http and SDK ports are different and hence the docs are wrong.

**Comment by akhilac1** [comment]
Resolved by PR #659
