### ISSUE TITLE
Binding Quickstart - which input and output should we use?

### ISSUE THREAD

**Issue by nirmash** [dapr/quickstarts#658]
Per this pool request (https://github.com/dapr/docs/pull/2368) we created a Quickstart for Bindings using Kafka for both input and output. This is not ideal as the functionality is the same as the PubSub Quickstart. I am researching other options and will suggest them on this issue and new pull request.

**Comment by paulyuk** [comment]
As a team we have been going with the following:
- input: cron (system)
- output: postgresql

Bindings are typically about inputs and outputs from 'external things'.  We like these because the amount of setup and account hookup is extremely low.

Thoughts?

**Comment by paulyuk** [comment]
Per your PR this is live now!
https://docs.dapr.io/getting-started/quickstarts/bindings-quickstart/
