### ISSUE TITLE
Show insights into the Cloud Events in the Pub/Sub tutorial

### ISSUE THREAD

**Issue by msfussell** [dapr/quickstarts#668]
The pub/sub tutorial can be improved by showing visibility into the Cloud Events that are being published on Redis streams. 
Simply
1) Attached to the Redis docker image 
`docker exec -it dapr_redis redis-cli`

2) Show the number of orders
`XLEN orders`

3) Show the details of each order in the stream events (below shows the first two events)
`XRANGE orders - + Count 2`

This would be added at the end of the self host section and just before the K8s section here https://github.com/dapr/quickstarts/tree/master/tutorials/pub-sub#run-in-kubernetes

**Comment by paulyuk** [comment]
I love this.  Thank you for contribution @shivanisinghnitp 

Just I believe it belongs in our docs and not the quickstarts.  It would be a good "next steps" for quickstarts, so happy to link to it. @msfussell

**Comment by shivanisinghnitp** [comment]
Thank you @paulyuk . 

@msfussell please look into it and let me know if I should move it to "next steps" of Pub-Sub docs.
