### ISSUE TITLE
Why Pub-Sub url does not redirect to an external page

### ISSUE THREAD

**Issue by yash-nisar** [dapr/quickstarts#711]
## Expected Behavior
On clicking the link to the "Why Pub-Sub" keyword on the [README](https://github.com/dapr/quickstarts/blob/master/pub_sub/csharp/sdk/README.md#why-pub-sub), I should be redirected to an external page to get more information on why pub sub would be a good choice for your software architecture.

## Actual Behavior
The url points to the same [README ](https://github.com/dapr/quickstarts/blob/master/pub_sub/csharp/sdk/README.md#why-pub-sub)page which should not be the case.

## Steps to Reproduce the Problem
Click on Why Pub-Sub hyperlink on the [README](https://github.com/dapr/quickstarts/blob/master/pub_sub/csharp/sdk/README.md#why-pub-sub).

**Comment by paulyuk** [comment]
Thank you @yash-nisar I agree with your feedback.  Let's schedule a fix.  If you would like to suggest and PR a change we would of course welcome that.  

What do you think about this URL target instead? https://docs.dapr.io/developing-applications/building-blocks/pubsub/pubsub-overview/

**Comment by yash-nisar** [comment]
Yup, the URL target you pointed looks good. I'll open a PR shortly

**Comment by yash-nisar** [comment]
@paulyuk Can you assign this issue to me in the meanwhile ?

**Comment by paulyuk** [comment]
Thank you @yash-nisar
