### ISSUE TITLE
Pubsub checks fail on invalid route

### ISSUE THREAD

**Issue by paulyuk** [dapr/quickstarts#715]
We're seeing a new regression where checks fail only for PubSub python quickstart.

The root seems to be this invalid route being called:

`		== APP == 127.0.0.1 - - [27/Jul/2022 16:44:32] "POST /route-orderpubsub-orders HTTP/1.1" 404 -
		time="2022-07-27T16:44:32.711458639Z" level=error msg="non-retriable error returned from app while processing pub/sub event a1638f44-2da6-43eb-b687-149af67ec92f: <!doctype html>\n<html lang=en>\n<title>404 Not Found</title>\n<h1>Not Found</h1>\n<p>The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.</p>\n. status code returned: 404" app_id=order-processor instance=fv-az445-222 scope=dapr.runtime type=log ver=1.8.2`

See more details here:
https://github.com/dapr/quickstarts/runs/7544552657?check_suite_focus=true

**Comment by amulyavarote** [comment]
The examples are running successfully on my local system after restarting the system.

**Comment by paulyuk** [comment]
Fixed by #725
