### ISSUE TITLE
Dapr Workflow Quickstart

### ISSUE THREAD

**Issue by nyemade-uversky** [dapr/quickstarts#733]
**Description:** 
Show Dapr workflow examples in .NET, Go and Java (the supported SDKs)

**Requirements: Quickstart covers**

- [ ] Perquisites needed to get started
- [ ] Process of invoking the Dapr workflow. Can use a simple app with a set of activities that process tasks
- [ ] Examples in .NET, Go and Java (the supported SDKs)

**Comment by paulyuk** [comment]
let's def consider for 1.10 as the feature is stable and we can use it.  I'd love your help figuring out the specific scenario to showcase.

**Comment by nyemade-uversky** [comment]
@hhunter-ms and @RyanLettieri putting this on both your radars as part of the requirements for Workflow API

**Comment by hhunter-ms** [comment]
@cgillum

**Comment by greenie-msft** [comment]
@RyanLettieri , @nyemade-uversky  QuickStart maintainers discussed priority for 1.10:

- Scenario - order processing workflow
- Demonstrate more than just logging, for example - sequence, fan-in/fan-out
- Thorough README with instructions/tests on how to execute locally
- (Reach goal) Able to execute in K8s
- Examples for .NET, Python, JS

**Comment by cgillum** [comment]
> Demonstrate more than just logging, for example - sequence, fan-in/fan-out

I spoke to @RyanLettieri about the sample, and I don't think fan-out/fan-in is a good match for an order processing workflow. Rather, a separate data processing workflow sample is probably better suited for that.

However, I think it would make sense for us to incorporate state store interactions as well as error handling/compensation to make the order processing workflow more interesting. Ryan's currently looking into this.

> Examples for .NET, Python, JS

Can we clarify the expectation for v1.10? Currently we only have an SDK in .NET. The order processing app is also currently a single project. Is the intent to break it up into multiple projects, e.g., a JS frontend app that uses the Dapr API (HTTP) to start workflows that run in the .NET app? Maybe we could add Python as an app that consumes pub/sub messages emitted by the workflow?

**Comment by paulyuk** [comment]
Do we still need this or are we covered by #787 ? @nyemade-uversky @cgillum

**Comment by msfussell** [comment]
Closing since done in v1.10 for dotnet.
