### ISSUE TITLE
Reduce parallelism and split validation per language

### ISSUE THREAD

**Issue by artursouza** [dapr/quickstarts#788]
Today, there is one validation workflow per building block (new quickstarts) and within each there is a multiplication matrix for programming language and protocol/SDK. It helps to avoid validation to fail due to left over state from a previous scenario, but this causes too many jobs to be triggered, exhausting the available workers for other workflows.

Instead, split the workflows per programming language. Within each workflow, multiplex only per protocol and have a loop within the workflow to run validation for each building block. This way, there would still be isolation for each building block but reduced number of jobs triggered.

Summary:
+ Move from workflow file per building block to workflow per language in `.github/workflows`
+ Matrix is only for [sdk, http] (variant)
+ Building blocks run in sequence in a single step with a loop that understands the folder structure, so when a new building block quickstart is added for a language, it is automatically picked up without requiring code changes:
```bash
for building_block in `ls -1`; do # get list of building blocks from folders or from env variable in global.env
  # TODO: add check if folder exists.
  cd $building_block/$language/$variant
  make validate 
  cd ../../../
done
```

**Comment by paulyuk** [comment]
I like it that there's still some split so that:
- one workflow isn't too long
- the isolation prevents 1 flakey issue taking down the whole matrix

The split by Building block has been good so that any new building block we introduce, does not affect the others that are in good shape.  We'll add building blocks more often than adding languages.  Also you sort of have to "test in main" with these things, so i think authoring will get harder.  but if it makes daily runtime better I'm still good with trying something and optimizing that way.

**Comment by artursouza** [comment]
I think it can be done in a way that adding a new building block does not require any change to the workflows. I also noticed that by isolating per programming language, we can separate the initial setup.

**Comment by paulyuk** [comment]
I reviewed the revised approach above and agree with it.  Approved.

**Comment by mukundansundar** [comment]
@artursouza Are we still going to multiplex on the OS platform?

**Comment by artursouza** [comment]
I think so. That needs to be a separate run no matter what. Also, it can help us know when the automation is done and no manual validation is required for a given OS - mostly Windows requires manual validation right now.

**Comment by paulyuk** [comment]
Note @ASHIQUEMD is signing on to drive this.  Thank you MD!

**Comment by msfussell** [comment]
@ASHIQUEMD @paulyuk - can we close this issue?

**Comment by ASHIQUEMD** [comment]
Yes @msfussell, we can close this. This completed as part of [this PR](https://github.com/dapr/quickstarts/pull/805).
