### ISSUE TITLE
PubSub csharp fails with "unknown flag --resources-path"

### ISSUE THREAD

**Issue by ridomin** [dapr/quickstarts#802]
The README has this instruction

```bash
dapr run --app-id order-processor
 --resources-path ../../../components/ --app-port 7002 -- dotnet run --project .
```
that fails with

```text
unknown flag: --resources-path
```
I guess it should be "components-path".

```
dapr --version
CLI version: 1.9.1
Runtime version: 1.9.6
```

**Comment by mukundansundar** [comment]
`--resources-path` was added as part of 1.10 version in CLI. Please try with that version.

**Comment by msfussell** [comment]
@ridomin Closing this issue, if you have used this on 1.10. If running into this still, reopen.
