### ISSUE TITLE
workflow terminate method is not work

### ISSUE THREAD

**Issue by gongxh13** [dapr/quickstarts#807]
When I use this demo https://github.com/gongxh13/openfunction-demo/tree/main/dapr/net/call-workflow to try workflow in k8s environment, I use two pods, one is for handler http request and call workflow start/terminate and query status api, another pod is official dotnet sdk example for provide workflow.
## Expected Behavior
Can call workflow relative api.

## Actual Behavior
terninate api is failed, error tell me not provide dapr-app-id as below
```
{"errorCode":"ERR_DIRECT_INVOKE","message":"failed getting app id either from the URL path or the header dapr-app-id"
```
And I add dapr-app-id in header request, and get another error as below
```
{"errorCode":"ERR_DIRECT_INVOKE","message":"fail to invoke, id: call-workflow-order-processor, err: rpc error: code = Internal desc = app channel is not initialized"
```

## Steps to Reproduce the Problem
You can direct use https://github.com/gongxh13/openfunction-demo/tree/main/dapr/net/call-workflow demo.

**Comment by msfussell** [comment]
@cgillum @RyanLettieri  - PTAL at this work issue.

**Comment by msfussell** [comment]
@gongxh13 - Can you try this out on the v1.11 release or the lastest v1.12 RC release out now. We suspect this is due to an SDK/Runtime mismatch.

**Comment by msfussell** [comment]
@gongxh13 - Did not hear back, so closing this issue. Please reopen if needed
