### ISSUE TITLE
Update JavaScript SDK to 3.0.0

### ISSUE THREAD

**Issue by shubham1172** [dapr/quickstarts#818]
## Describe the feature

JS-SDK had a new release with breaking changes, see https://github.com/dapr/js-sdk/releases/tag/v3.0.0, quickstarts need to be updated to reflect the same.

**Comment by msfussell** [comment]
@wralith @shubham1172 - Have this issue been fixed in the Quickstarts?

**Comment by shubham1172** [comment]
@msfussell the PR is open here, PTAL https://github.com/dapr/quickstarts/pull/824

**Comment by paulyuk** [comment]
Merged fix by [wralith](https://github.com/wralith)
