### ISSUE TITLE
Choosing between binding and pubsub 

### ISSUE THREAD

**Issue by GowriVenk** [dapr/quickstarts#834]
## Ask your question here
Hi i need to subscribe to an event hub within our organisation and i was thinking to use pubsub. I noticed dapr also has bindings and have seen some blogs using binding to event hub. It isn't very clear when you use which api.  Please can i get  a clear pointers to pros and cons of each to help make that decision?

**Comment by msfussell** [comment]
@GowriVenk - Please post this question on the Dapr Discord pub/sub channel here https://discord.com/channels/778680217417809931/901141467840524289

In a nutshell, pub/sub API provides messaging capabilities and the bindings are simply a way to call onto an API, but do not have all the benefits described here https://docs.dapr.io/developing-applications/building-blocks/pubsub/pubsub-overview/#features
