### ISSUE TITLE
Missing Content-Type: application/json Header in sample.http Causes Uncaught Error

### ISSUE THREAD

**Issue by ehalsey** [dapr/quickstarts#835]
## Expected Behavior

Sending the POST request in the tutorials\hello-world\node\sample.http file should result in:
== APP == Got a new order! Order ID: 42
== APP == Successfully persisted state.

## Actual Behavior

Sending the request via the sample.http file returns:
== APP == D:\source\quickstarts\tutorials\hello-world\node\app.js:43
== APP ==     const orderId = data.orderId;
== APP ==                          ^
== APP == 
== APP == TypeError: Cannot read properties of undefined (reading 'orderId')
== APP ==     at D:\source\quickstarts\tutorials\hello-world\node\app.js:43:26
== APP ==     at Layer.handle [as handle_request] (D:\source\quickstarts\tutorials\hello-world\node\node_modules\express\lib\router\layer.js:95:5)
== APP ==     at next (D:\source\quickstarts\tutorials\hello-world\node\node_modules\express\lib\router\route.js:137:13)
== APP ==     at Route.dispatch (D:\source\quickstarts\tutorials\hello-world\node\node_modules\express\lib\router\route.js:112:3)
== APP ==     at Layer.handle [as handle_request] (D:\source\quickstarts\tutorials\hello-world\node\node_modules\express\lib\router\layer.js:95:5)
== APP ==     at D:\source\quickstarts\tutorials\hello-world\node\node_modules\express\lib\router\index.js:281:22
== APP ==     at Function.process_params (D:\source\quickstarts\tutorials\hello-world\node\node_modules\express\lib\router\index.js:341:12)
== APP ==     at next (D:\source\quickstarts\tutorials\hello-world\node\node_modules\express\lib\router\index.js:275:10)
== APP ==     at jsonParser (D:\source\quickstarts\tutorials\hello-world\node\node_modules\express\node_modules\body-parser\lib\types\json.js:119:7)
== APP ==     at Layer.handle [as handle_request] (D:\source\quickstarts\tutorials\hello-world\node\node_modules\express\lib\router\layer.js:95:5)
The App process exited with error code: exit status 1

Using v0.25.1 of Huachao Mao REST Client

## Steps to Reproduce the Problem

Install v0.25.1 of the REST Client and send the POST request at the top of the tutorials\hello-world\node\sample.http

**Comment by ehalsey** [comment]
Happy to submit a PR for this if that helps.

**Comment by msfussell** [comment]
@ehalsey - Yes, please. It would be good if you could submit a PR

**Comment by msfussell** [comment]
Closing issue
