### ISSUE TITLE
Config API QuickStart - Tracking issue to update the Quickstarts with new version of SDKs once they released

### ISSUE THREAD

**Issue by rabollin** [dapr/quickstarts#847]
Since Config API has moved to stable and have a change in API version causing breaking changes, there will be new version of SDKs to be released. It is a tracking issue to update the Configuration API QuickStart to refresh with new version of SDK once the SDKs are released.

**Comment by paulyuk** [comment]
Note all QS's are already updated to RC versions per #867

**Comment by shivamkm07** [comment]
> Note all QS's are already updated to RC versions per #867

Will update to stable versions once all SDKs are released.

**Comment by shivamkm07** [comment]
\assign
