### ISSUE TITLE
Add SDK example for Service Invocation that shows DaprClient.CreateInvokeHttpClient();

### ISSUE THREAD

**Issue by msfussell** [dapr/quickstarts#888]
Currently there are HTTP examples for service invocation, that show `httpclient` here https://github.com/dapr/quickstarts/blob/master/service_invocation/csharp/http/checkout/Program.cs

 However the preferred way of using this via the SDK using `DaprClient.CreateInvokeHttpClient();` is not covered and this should be where we direct users. It is described here https://learn.microsoft.com/en-us/dotnet/architecture/dapr-for-net-developers/service-invocation#invoke-http-services-using-httpclient 

The docs in .NET also need updating here https://docs.dapr.io/developing-applications/sdks/dotnet/dotnet-client/ to show this method for both HTTP and SDK for Service Invocation.

**Comment by joebowbeer** [comment]
Close this?

I think both links have been addressed.

**Comment by paulyuk** [comment]
Agree
