### ISSUE TITLE
pub_sub: go: publisher sleeps for 1 millisecond instead of 1 second

### ISSUE THREAD

**Issue by paskozdilar** [dapr/quickstarts#890]
## Expected Behavior

In pub/sub Go example, I expect Go publishers to behave consistently with other language examples: to sleep for 1 second between each order publish.

## Actual Behavior

In pub/sub Go example, Go publishers sleep for 1 millisecond between each order publish.

## Steps to Reproduce the Problem

1. Set up Dapr if not set already (`dapr init`)
2. Open path in this repository `pub_sub/go/sdk/checkout` in a terminal
3. Execute command `go build . && dapr run --app-id checkout --app-protocol http --dapr-http-port 3500 --resources-path ../../../components -- go run .`
4. Observe how the publisher publishes all 10 order messages instantly instead of waiting for 1 second between each one.

**Comment by rabollin** [comment]
This issue can be closed on the PR is merged.
