### ISSUE TITLE
(docs correction) Remove outdated comment from config quickstart 

### ISSUE THREAD

**Issue by awhiteside1** [dapr/quickstarts#892]
# Problem
The [quick start for configuration block in javascript](https://github.com/dapr/quickstarts/blob/dfde545821683f794faedaa895fbab863df3e3a4/configuration/javascript/sdk/order-processor/index.js#L3) incorrectly says that only GRPC is supported, however the [js SDK has an HTTP example](https://github.com/dapr/js-sdk/blob/main/examples/configuration/src/index.ts). 

# Task
Assuming the sdk example works, remove the comment from the quickstart, and potentially link to the HTTP example.

**Comment by alicejgibbons** [comment]
@awhiteside1 this is still correct as the Dapr SDK itself does not support HTTP but only gRPC protocol. For instance if you try instantiating a DaprClient as follows, you will get the error:
`== APP == Could not get config item, err:Error: HTTP is currently not supported.`

``` javascript
const communicationProtocol = CommunicationProtocolEnum.HTTP;
const client = new DaprClient({daprHost, daprPort, const communicationProtocol});
```

**Comment by paulyuk** [comment]
Per Alice I think we shoudl leave this for now.  Please reopen if you disagree
