### ISSUE TITLE
Fix broken link references in Observability tutorial 

### ISSUE THREAD

**Issue by msfussell** [dapr/quickstarts#895]
In this tutorial https://github.com/dapr/quickstarts/tree/master/tutorials/observability
The build is failing due to broken links. See below.
![image](https://github.com/dapr/quickstarts/assets/11199644/37cf92d7-6eac-433c-91b7-741af87656ae)

https://docs.dapr.io/developing-applications/building-blocks/observability/tracing-overview/ needs to be replaced with this link
https://docs.dapr.io/operations/monitoring/tracing/

There are two references to fix one at the start and one at the end

**Comment by MregXN** [comment]
```
External link validation:
        https://docs.dapr.io/concepts/observability-concept/ Status: 200
        https://docs.dapr.io/operations/observability/tracing/tracing-overview/ Status: 200
        https://opencensus.io/ Status: 200
        https://zipkin.io/ Status: 200
        https://hub.docker.com/r/openzipkin/zipkin/ Status: 200
        https://zipkin.io/zipkin-api/ Status: 200
        https://docs.dapr.io/operations/hosting/kubernetes/kubernetes-deploy/ Status: 200
        https://docs.dapr.io/getting-started/tutorials/configure-state-pubsub/#step-1-create-a-redis-store Status: 200
        http://localhost:19411 Status: Ignored
        https://github.com/dapr/quickstarts/blob/master/tutorials/distributed-calculator/deploy/react-calculator.yaml#L36 Status: 200
        https://github.com/dapr/quickstarts/tree/master/tutorials/distributed-calculator Status: 200
        http://localhost:19411 Status: Ignored
        https://docs.dapr.io/concepts/observability-concept/ Status: 200
        https://docs.dapr.io/operations/observability/tracing/tracing-overview/ Status: 200
```

This is the log after I run `make validate` and it seems that the issue you mentioned is not existed. Maybe you could try again with the latest version of dapr/quickstarts.

**Comment by MregXN** [comment]
Sorry I just found the PR #896 of fixing this issue. Maybe we could close this issue directly.

**Comment by msfussell** [comment]
Yes, this is fixed. Closing
