### ISSUE TITLE
Golang service_invocation/order-processor has an incorrect port

### ISSUE THREAD

**Issue by hughxia** [dapr/quickstarts#899]
## Expected Behavior

According to the [official documentation](https://docs.dapr.io/getting-started/quickstarts/serviceinvocation-quickstart/) and comments, order-processor run with port 6001.
![image](https://github.com/dapr/quickstarts/assets/32231985/b35994c0-e230-4e7e-936f-031319a62940)

## Actual Behavior

order-processor run with port 6006

## Steps to Reproduce the Problem

just go run it

**Comment by hughxia** [comment]
I saw the commit: ea182d5610a911b1d3021e73b760a795682f6d26, maybe the comments and official document is not up-to-date.

**Comment by rabollin** [comment]
This issue can be closed once the PR is merged.
