### ISSUE TITLE
Demo workflow failed 

### ISSUE THREAD

**Issue by Prazzy** [dapr/quickstarts#901]
Hi, I tried to run this workflow locally, but received below error. 
https://github.com/dapr/python-sdk/tree/master/examples/demo_workflow

== APP == 	details = "error starting workflow 'hello_world_wf': unable to start workflow: failed to start orchestration: error finding address for actor type dapr.internal.default.orderapp.workflow with id exampleInstanceID"
== APP == 	debug_error_string = "UNKNOWN:Error received from peer ipv4:127.0.0.1:50001 {grpc_message:"error starting workflow \'hello_world_wf\': unable to start workflow: failed to start orchestration: error finding address for actor type dapr.internal.default.orderapp.workflow with id exampleInstanceID", grpc_status:13, created_time:"2023-08-30T17:19:44.361784-04:00"}"

Any help would be greatly appreciated

**Comment by Prazzy** [comment]
Same issue for https://github.com/dapr/quickstarts/tree/master/workflows/csharp/sdk also..

== APP == Unhandled exception. Dapr.DaprException: Start Workflow operation failed: the Dapr endpoint indicated a failure. See InnerException for details.
== APP ==  ---> Grpc.Core.RpcException: Status(StatusCode="Internal", Detail="error starting workflow 'OrderProcessingWorkflow': unable to start workflow: failed to start orchestration: error finding address for actor type dapr.internal.default.order-processor123.workflow with id b745624f")
== APP ==    at Dapr.Client.DaprClientGrpc.StartWorkflowAsync(String workflowComponent, String workflowName, String instanceId, Object input, IReadOnlyDictionary`2 workflowOptions, CancellationToken cancellationToken)
== APP ==    --- End of inner exception stack trace ---
== APP ==    at Dapr.Client.DaprClientGrpc.StartWorkflowAsync(String workflowComponent, String workflowName, String instanceId, Object input, IReadOnlyDictionary`2 workflowOptions, CancellationToken cancellationToken)
== APP ==    at Program.<Main>$(String[] args) in /Users/pshilavantar/Documents/code/dapr-apps/quickstarts/workflows/csharp/sdk/order-processor/Program.cs:line 54
== APP ==    at Program.<Main>(String[] args)

**Comment by rabollin** [comment]
Hi - @Prazzy - can you confirm what OS you are running this sample?

**Comment by Prazzy** [comment]
@rabollin I am using MacOS and Dapr 1.11. Yeah very strange. It did work initially but started failing after making some modifications. So it has to do with the changes I made. However, tried reverting my code changes, but still the same issue. Since other workflow code is working for me now, I am not looking into it now. So closing it for now.
