### ISSUE TITLE
Workflow Java SDK Code Sample

### ISSUE THREAD

**Issue by nyemade-uversky** [dapr/quickstarts#903]
**_Moving existing tracking issue for the java code sample into the quickstarts repo._**

**What content needs to be created or modified?**
We need to create java code sample for the workflow Java SDK QuickStart. This issue defines the criteria needed in a java code sample. There is a separate issue for the QuickStart itself.

Main workflow java sdk docs issue here: #3567  

**Describe the solution you'd like**
We'll need a java sample that exactly mimics the same structure as the existing workflow samples for .NET and python.

I'll reference the .NET sample for my examples below:

1. The java program.cs file should have the exact same steps as the [.NET quickstart program.cs](https://github.com/dapr/quickstarts/blob/master/workflows/csharp/sdk/order-processor/Program.cs) file. Even down to the number of items purchased, and the item chosen)
2. Activities, and workflows should match those in [.NET quickstart](https://github.com/dapr/quickstarts/tree/master/workflows/csharp/sdk/order-processor). For example, for the java sdk we'd also want the same exact 4 activities, activity names, workflow etc.

**Additional context**
#3567 
dapr/quickstarts#898
https://github.com/dapr/java-sdk/pull/880

**Comment by nyemade-uversky** [comment]
@hhunter-ms  and @skyao I'm moving this issue into the quickstarts repo instead. @skyao could you assign this to yourself?

**Comment by skyao** [comment]
hi, @nyemade-uversky  I had submitted the PR of workflow quick start in java sdk and waiting for review and merge.

I will continue to prepare the content in dapr docs about dapr workflow with java sdk.

**Comment by nyemade-uversky** [comment]
@skyao could you actually close this PR and reopen it in the quickstart repo instead? We'd like the code sample for wf to live in the same repo with the actual quickstart.

**Comment by msfussell** [comment]
Completed
