### ISSUE TITLE
Add multi-app run file for javascript pubsub quickstarts

### ISSUE THREAD

**Issue by alicejgibbons** [dapr/quickstarts#910]
Add a [multi-app run configuration file](https://docs.dapr.io/developing-applications/local-development/multi-app-dapr-run/multi-app-overview/) to the SDK and HTTP pubsub quickstarts in javascript to start both order-processor and checkout apps at the same time.

Quickstarts:
- [ ] HTTP: https://github.com/dapr/quickstarts/tree/master/pub_sub/javascript/http
- [ ]  SDK: https://github.com/dapr/quickstarts/tree/master/pub_sub/javascript/sdk

**Comment by hhunter-ms** [comment]
this was resolved here: #874
