### ISSUE TITLE
[Workflow] Quickstart for JavaScript SDK

### ISSUE THREAD

**Issue by msfussell** [dapr/quickstarts#964]
Creating a Workflow sample in the Quickstarts based on this docs PR. https://github.com/dapr/docs/pull/3896

**Comment by mikeee** [comment]
Is this for the Go SDK?

**Comment by paulyuk** [comment]
@kaibocai

**Comment by paulyuk** [comment]
@kaibocai - The ask is that we closely transpose the content from this [C# workflow quickstart](https://github.com/dapr/quickstarts/tree/master/workflows/csharp/sdk) to Javascript, of course in the idioms of JS.  That means readme's, steps, files, data, strings, etc are the same unless they MUST be different for js.

**Comment by paulyuk** [comment]
Fixed by #989
