### ISSUE TITLE
Update the golang validation workflow

### ISSUE THREAD

**Issue by mikeee** [dapr/quickstarts#968]
## Describe the feature

The validation workflow should be updated to `setup-go@v5` and make use of the `go.mod` file for the version which should also be bumped to 1.20.

This would be a good first issue for contributors.

**Comment by rochabr** [comment]
@mikeee I can take this one. Can you add a little bit more context?

**Comment by mikeee** [comment]
Whoops, I completed this a couple of months back. Sorry! 

https://github.com/dapr/quickstarts/pull/986
