### ISSUE TITLE
Missing Kubernetes Quick Start

### ISSUE THREAD

**Issue by tshaiman** [dapr/quickstarts#972]
## Describe the feature

1. going to the Pub-Sub Quick start you have 5 language options 
https://docs.dapr.io/getting-started/quickstarts/pubsub-quickstart/#pubsubyaml-component-file

2. the sample assume you are going to run the Dapr locally using `dapr init` which installs the side cars on your system

** Request ** : Create a more cloud-native apporach sample. show how to build the diffrent component Dockerfiles / and YAML manifast , explain what happens when Dapr is installed on K8s Cluster . 
Seperate the installation guides between different cloud providers , as for example in Azure AKS Dapr is actually an extension

Then , demonstrate how the State Store needs to be installed . suppose you want to use Rabbit -> you have to install Rabbit Helm chart , which should be part of the guide.

supposed you want to use Redis -> well that requires either managed redis by a cloud provider or helm install of the chart. 

all those pre-requisites are not present today at the quick start which assumes a naive approach : Run locally . 
its nice but does not leverge the true power of the platform .

when it comes to deploying the pods that communicate with each other , its maybe good approach to provide with 2 Deployment.yaml files that does all the registation of the pub-sub as part of their K8s manifast files ? 

its much bigger impact to show this microservice architecture framework on ........... well , microservices.

**Comment by paulyuk** [comment]
Hey @tshaiman, this is a very good idea that I want to do this year.  

Meanwhile, could you please take a look at this [Hello Kubernetes (cloud native) Tutorial](https://github.com/dapr/quickstarts/tree/master/tutorials/hello-kubernetes) and let me know what you think?  We simplified it recently to use "multi run app file" for kubernetes.  It is Hello World ish tho still and not as cool as PubSub.

**Comment by tshaiman** [comment]
@paulyuk  : This is great ! Let me know if I can assist in contributing to the K8s tutorials - I'm really passionate to do so.
regarding the hello world - I've seen it and had some other remarks on the docs . I still think that the "multi run app file" although being very cool may not fit the Cloud native way , as it forces you to use Dapr CLI while many CI/CD tools will most likey leverage helm . 
my other remark was around the need to install / use Redis or any other state store on a different namespace then the app , and I think there should be a note on how to do that . will that change the "service" notation ( e.g service.namespace ) and/or the secret fetching .

thanks again - this is great stuff !

**Comment by tshaiman** [comment]
p.s : 
There are two versions of .NET SDK Workflow samples , in two different repos : 

https://github.com/dapr/quickstarts/tree/master/workflows/csharp/sdk/order-processor


and 

https://github.com/dapr/dotnet-sdk/tree/master/examples/Workflow/WorkflowConsoleApp

which is the "Lastest-And-Greatest" ?

**Comment by paulyuk** [comment]
> p.s : There are two versions of .NET SDK Workflow samples , in two different repos :
> 
> https://github.com/dapr/quickstarts/tree/master/workflows/csharp/sdk/order-processor
> 
> and
> 
> https://github.com/dapr/dotnet-sdk/tree/master/examples/Workflow/WorkflowConsoleApp
> 
> which is the "Lastest-And-Greatest" ?

Answered in https://github.com/dapr/quickstarts/issues/981 -- thank you!

**Comment by paulyuk** [comment]
> @paulyuk : This is great ! Let me know if I can assist in contributing to the K8s tutorials - I'm really passionate to do so. regarding the hello world - I've seen it and had some other remarks on the docs . I still think that the "multi run app file" although being very cool may not fit the Cloud native way , as it forces you to use Dapr CLI while many CI/CD tools will most likey leverage helm . my other remark was around the need to install / use Redis or any other state store on a different namespace then the app , and I think there should be a note on how to do that . will that change the "service" notation ( e.g service.namespace ) and/or the secret fetching .
> 
> thanks again - this is great stuff !

Hi @tshaiman - I would love to take you up on a kubernetes quickstart, and/or enhancement to hello world.  I get what you mean about dapr.yaml.  Btw, for me this dapr.yaml (multi app run file) is all about an "inner loop tool" to run on your local machine, and I don't feel it should be used for CI/CD or later deployment stages per se.  I assume you'd use helm etc for those.  What's your take on this?

**Comment by tshaiman** [comment]
@paulyuk  : my take is that there should be Zero-To-Hero pure K8s guide that leverage Helm / Kustomize and ( maybe later) 
GitOps with Either Flux or ArgoCD , while it can be written in general , or per-cloud provider 

Let me know if you need some working hands here ;-)

**Comment by paulyuk** [comment]
awesome.  let's leave this open as a proposal for an e2e quickstart for dapr on kubernetes.  would you like to lead this off with requirements you have for it?

**Comment by tshaiman** [comment]
it will be my honor . 
how can we start this contribution ? isnt someone else already assigned to it from community ?
