### ISSUE TITLE
Proposal: Upgrade C# quickstarts to .NET 8 LTS

### ISSUE THREAD

**Issue by paulyuk** [dapr/quickstarts#980]
.NET 8 is the new LTS, and .NET 6 is limited how much longer it will be supported.  It would be nice for the .NET community to have a refresh here.

The change is to update all 10 C# quickstarts (http and sdk versions) to .NET 8 LTS runtime in the .csproj.

**Comment by paulyuk** [comment]
@msfussell pls approve

**Comment by msfussell** [comment]
+ 1 Approved.

**Comment by paulyuk** [comment]
Done!
