### ISSUE TITLE
Its Not clear which is the most up-to-date-dotnet Workflow Sample

### ISSUE THREAD

**Issue by tshaiman** [dapr/quickstarts#981]
There are two versions of .NET SDK Workflow samples , in two different repos : 

https://github.com/dapr/quickstarts/tree/master/workflows/csharp/sdk/order-processor

and 

https://github.com/dapr/dotnet-sdk/tree/master/examples/Workflow/WorkflowConsoleApp

which is the "Lastest-And-Greatest" ?

**Comment by paulyuk** [comment]
Hi @tshaiman 

In principle quickstarts are meant to be the most official, best supported, most looked at samples.  They always cover all the languages.  SDK authors will also include examples as they author.  Sometimes there are brief moments where SDK examples are "ahead" while authors are improving their SDKs, but I also insist we get latest and greatest back into quickstarts.

@halspang @philliphoff @MregXN fyi.

Now, this [PR from @MregXN](https://github.com/dapr/quickstarts/pull/959) has been languishing until today so the quickstarts where stale showing which workflow client to use.  I just merged that to correct.  Thanks for pointing this out.

All good?

**Comment by tshaiman** [comment]
@paulyuk  absolutely ! 
thanks for that .

also , I will be more then happy to perform a full K8s Tutorial. I know there is "Hello Kubernetes" but I'm talking about full End-to-End.
( also in my opinion using the Dapr CLI in k8s scenarios is not applicable , as all should be deployed with Yaml / Helm / Kustomize and not with dedicated cli , as cool as it may be . )

keep on rocking !
