### ISSUE TITLE
Update Javascript quickstarts when javascript-sdk for 1.13 is available

### ISSUE THREAD

**Issue by paulyuk** [dapr/quickstarts#993]
@dapr/maintainers-js-sdk pls let me know when you have a 1.13 release/tag/drop and I'll make the updates.

this is a follow up to #992

**Comment by shubham1172** [comment]
Sure @paulyuk, once Dapr 1.13 releases, we will cut the SDK release and update here. You could also use our dev builds (from latest main branch) to test it meanwhile if required.
