### ISSUE TITLE
C# tests now fail because sidecar / app starts faster than tests expect now

### ISSUE THREAD

**Issue by paulyuk** [dapr/quickstarts#997]
Test failure here:
https://github.com/dapr/quickstarts/actions/runs/8175837581/job/22353889408#step:12:92

This is basically a timing issue rather than a functional error.

I'm playing with sleeps now.

**Comment by paulyuk** [comment]
Should be fixed by commit above.  validating now

**Comment by philliphoff** [comment]
Well, as I always say, when in doubt...lengthen the timeout.  :-)
